table Customers
	lineageTag: 2d24d5b8-100a-4ae5-bb1b-fcb30fd41e6c

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 35416fe2-523f-483f-9635-af88b2581199
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 48693319-3c36-4fa3-8c09-d9853c140cfb
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXLMyUxOVYrViVYyAvKcUvPAbGMg2zkjJx8iYwLkuSTmZabmKMXGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CustomerID = _t, CustomerName = _t]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"CustomerID", Int64.Type}, {"CustomerName", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
