table Dim
	lineageTag: 47b682c0-e36a-40d6-9632-b8a92c393bf0

	column Key
		dataType: int64
		formatString: 0
		lineageTag: f186e98c-1c00-4232-ac57-5850d0593cfc
		summarizeBy: count
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column X
		dataType: int64
		formatString: 0
		lineageTag: f87f1be6-c3a6-46a7-9891-69e89f442aa6
		summarizeBy: sum
		sourceColumn: X

		annotation SummarizationSetBy = Automatic

	partition Dim = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUTI0UIrViVYyAjKNIExjINMYyIwFAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Key = _t, X = _t]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"Key", Int64.Type}, {"X", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

