/// Contains test data for description persistence - Desktop authored.
table TableA

	/// Returns total sales - 
	/// 
	/// before adjustments.
	measure MeasureA = 100
		formatString: 0

	measure MeasureB = 200
		formatString: 0

	/// Customer's category: used for grouping.
	column ColumnA1
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: ColumnA1

		annotation SummarizationSetBy = Automatic

	column ColumnA2
		dataType: string
		summarizeBy: none
		sourceColumn: ColumnA2

		annotation SummarizationSetBy = Automatic

	partition TableA = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUUpUitWJVjICspLALGMgKxnMMgGyUpRiYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ColumnA1 = _t, ColumnA2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ColumnA1", Int64.Type}, {"ColumnA2", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
