// <auto-generated>
// Generated by scripts/Sync-DesignTokens.mjs. Do not edit by hand.
// Edit src/PbiAssure.Web/wwwroot/css/core.css or src/PbiAssure.Reporting/Styles/report.css
// and run: node scripts/Sync-DesignTokens.mjs
// </auto-generated>

namespace PbiAssure.Reporting;

/// <summary>
/// The PBI Assure design system as compiled text.
///
/// The browser application links these stylesheets as files. A generated report has to travel as
/// one self-contained document, so the same bytes are inlined into its head. Keeping a single
/// source for both is what stops the two surfaces drifting into different products.
/// </summary>
public static class DesignSystem
{
    /// <summary>Design tokens and the primitives shared with the browser application.</summary>
    public const string Core = """
        /* PBI Assure design system — tokens and shared primitives.
           Shared verbatim by the browser application and the generated HTML report so that both
           surfaces stay one product. Edit this file, then run: node scripts/Sync-DesignTokens.mjs
           DesignSystemSourceTests fails the build when the copies drift. */

        /* ---------------------------------------------------------------- tokens */

        :root {
          color-scheme: light;

          --pa-font-sans: "Segoe UI Variable Text", "Segoe UI", system-ui, -apple-system, Inter, "Helvetica Neue", Arial, sans-serif;
          --pa-font-display: "Segoe UI Variable Display", "Segoe UI", system-ui, -apple-system, Inter, "Helvetica Neue", Arial, sans-serif;
          --pa-font-mono: "Cascadia Mono", "Cascadia Code", ui-monospace, "SF Mono", "JetBrains Mono", Consolas, "Liberation Mono", monospace;

          --pa-t-3xs: 0.6875rem;
          --pa-t-2xs: 0.75rem;
          --pa-t-xs: 0.8125rem;
          --pa-t-sm: 0.875rem;
          --pa-t-md: 0.9375rem;
          --pa-t-lg: 1.0625rem;
          --pa-t-xl: 1.3125rem;
          --pa-t-2xl: 1.625rem;
          --pa-t-3xl: 2rem;

          --pa-s1: 0.25rem;
          --pa-s2: 0.5rem;
          --pa-s3: 0.75rem;
          --pa-s4: 1rem;
          --pa-s5: 1.25rem;
          --pa-s6: 1.5rem;
          --pa-s7: 2rem;
          --pa-s8: 2.5rem;
          --pa-s9: 3.5rem;

          --pa-r1: 3px;
          --pa-r2: 5px;
          --pa-r3: 8px;

          --pa-fast: 110ms;
          --pa-normal: 170ms;
          --pa-ease: cubic-bezier(0.2, 0, 0, 1);

          /* Neutral ramp. Cool-cast rather than pure grey: technical without reading as corporate navy. */
          --pa-canvas: #f7f8fa;
          --pa-surface: #ffffff;
          --pa-surface-2: #f2f4f7;
          --pa-surface-3: #e8ebf0;
          --pa-line: #e2e6ec;
          --pa-line-strong: #cdd4de;
          --pa-text: #101828;
          --pa-text-2: #475467;
          --pa-text-3: #667085;
          --pa-on-accent: #ffffff;

          /* Interaction. Indigo is reserved for "you can act on this" and is never a status. */
          --pa-accent: #4f46e5;
          --pa-accent-hover: #4038c9;
          --pa-accent-soft: #eef0ff;
          --pa-accent-line: #c5c8fb;
          --pa-focus: #4f46e5;
          --pa-focus-contrast: #ffffff;

          /* Severity family: findings. */
          --pa-error: #b42318;
          --pa-error-soft: #fef3f2;
          --pa-error-line: #fbcfca;
          --pa-warning: #b54708;
          --pa-warning-soft: #fffaeb;
          --pa-warning-line: #f5dda0;
          --pa-review: #7e22ce;
          --pa-review-soft: #faf5ff;
          --pa-review-line: #e5d2fb;
          --pa-info: #026aa2;
          --pa-info-soft: #f0f9ff;
          --pa-info-line: #b3ddf5;
          --pa-neutral: #475467;
          --pa-neutral-soft: #f2f4f7;
          --pa-neutral-line: #dfe3ea;

          /* Usage family: a confidence ramp from evidenced use to no evidence of use. */
          --pa-used: #067647;
          --pa-used-soft: #ecfdf3;
          --pa-used-line: #a9e5c4;
          --pa-indirect: #0f766e;
          --pa-indirect-soft: #edfbf8;
          --pa-indirect-line: #a3e3d8;
          --pa-structural: #3e4c63;
          --pa-structural-soft: #eef1f6;
          --pa-structural-line: #d3dae5;
          --pa-branch: #a15c07;
          --pa-branch-soft: #fdf6e7;
          --pa-branch-line: #eeda9f;
          --pa-unused: #c11574;
          --pa-unused-soft: #fdf2fa;
          --pa-unused-line: #f7c8e6;

          --pa-shadow-1: 0 1px 2px rgb(16 24 40 / 7%);
          --pa-shadow-2: 0 6px 16px -4px rgb(16 24 40 / 12%), 0 2px 5px -2px rgb(16 24 40 / 8%);
        }

        /* Dark is designed, not inverted: the canvas recedes, surfaces step up towards the reader,
           borders carry less contrast than in light, and every status hue is re-picked at a lightness
           that reads on a dark ground without glowing. */
        :root[data-theme="dark"] {
          color-scheme: dark;

          --pa-canvas: #0b0e13;
          --pa-surface: #12181f;
          --pa-surface-2: #181f28;
          --pa-surface-3: #212a35;
          --pa-line: #27313d;
          --pa-line-strong: #3a4654;
          --pa-text: #e6edf6;
          --pa-text-2: #a4b1c3;
          --pa-text-3: #7f8d9f;
          --pa-on-accent: #0b0e13;

          --pa-accent: #8f90f8;
          --pa-accent-hover: #a8a9fb;
          --pa-accent-soft: #1b1f3a;
          --pa-accent-line: #3d3f7d;
          --pa-focus: #8f90f8;
          --pa-focus-contrast: #0b0e13;

          --pa-error: #ff9086;
          --pa-error-soft: #2a1413;
          --pa-error-line: #5d2721;
          --pa-warning: #f2b345;
          --pa-warning-soft: #291e0d;
          --pa-warning-line: #573c15;
          --pa-review: #c8a3f7;
          --pa-review-soft: #221a34;
          --pa-review-line: #47336d;
          --pa-info: #5cc0f0;
          --pa-info-soft: #0f2230;
          --pa-info-line: #1d4964;
          --pa-neutral: #a4b1c3;
          --pa-neutral-soft: #181f28;
          --pa-neutral-line: #3a4654;

          --pa-used: #5fd6a0;
          --pa-used-soft: #0e2419;
          --pa-used-line: #1d4e35;
          --pa-indirect: #4fd5c5;
          --pa-indirect-soft: #0c2422;
          --pa-indirect-line: #1a4d47;
          --pa-structural: #a2b2c9;
          --pa-structural-soft: #181f28;
          --pa-structural-line: #384453;
          --pa-branch: #e0b062;
          --pa-branch-soft: #251f0f;
          --pa-branch-line: #514320;
          --pa-unused: #f291c8;
          --pa-unused-soft: #2a1423;
          --pa-unused-line: #592847;

          --pa-shadow-1: 0 1px 2px rgb(0 0 0 / 40%);
          --pa-shadow-2: 0 8px 20px -6px rgb(0 0 0 / 60%), 0 2px 6px -2px rgb(0 0 0 / 45%);
        }

        @media (prefers-color-scheme: dark) {
          :root:not([data-theme="light"]) {
            color-scheme: dark;

            --pa-canvas: #0b0e13;
            --pa-surface: #12181f;
            --pa-surface-2: #181f28;
            --pa-surface-3: #212a35;
            --pa-line: #27313d;
            --pa-line-strong: #3a4654;
            --pa-text: #e6edf6;
            --pa-text-2: #a4b1c3;
            --pa-text-3: #7f8d9f;
            --pa-on-accent: #0b0e13;

            --pa-accent: #8f90f8;
            --pa-accent-hover: #a8a9fb;
            --pa-accent-soft: #1b1f3a;
            --pa-accent-line: #3d3f7d;
            --pa-focus: #8f90f8;
            --pa-focus-contrast: #0b0e13;

            --pa-error: #ff9086;
            --pa-error-soft: #2a1413;
            --pa-error-line: #5d2721;
            --pa-warning: #f2b345;
            --pa-warning-soft: #291e0d;
            --pa-warning-line: #573c15;
            --pa-review: #c8a3f7;
            --pa-review-soft: #221a34;
            --pa-review-line: #47336d;
            --pa-info: #5cc0f0;
            --pa-info-soft: #0f2230;
            --pa-info-line: #1d4964;
            --pa-neutral: #a4b1c3;
            --pa-neutral-soft: #181f28;
            --pa-neutral-line: #3a4654;

            --pa-used: #5fd6a0;
            --pa-used-soft: #0e2419;
            --pa-used-line: #1d4e35;
            --pa-indirect: #4fd5c5;
            --pa-indirect-soft: #0c2422;
            --pa-indirect-line: #1a4d47;
            --pa-structural: #a2b2c9;
            --pa-structural-soft: #181f28;
            --pa-structural-line: #384453;
            --pa-branch: #e0b062;
            --pa-branch-soft: #251f0f;
            --pa-branch-line: #514320;
            --pa-unused: #f291c8;
            --pa-unused-soft: #2a1423;
            --pa-unused-line: #592847;

            --pa-shadow-1: 0 1px 2px rgb(0 0 0 / 40%);
            --pa-shadow-2: 0 8px 20px -6px rgb(0 0 0 / 60%), 0 2px 6px -2px rgb(0 0 0 / 45%);
          }
        }

        /* ------------------------------------------------------------- foundation */

        *, *::before, *::after { box-sizing: border-box; }

        body {
          margin: 0;
          background: var(--pa-canvas);
          color: var(--pa-text);
          font-family: var(--pa-font-sans);
          font-size: var(--pa-t-md);
          line-height: 1.5;
          -webkit-font-smoothing: antialiased;
          text-size-adjust: 100%;
        }

        h1, h2, h3, h4, h5, h6 {
          font-family: var(--pa-font-display);
          font-weight: 600;
          letter-spacing: -0.015em;
          line-height: 1.25;
        }

        code, pre, kbd, samp { font-family: var(--pa-font-mono); }
        code { font-size: 0.9em; overflow-wrap: anywhere; }

        a { color: var(--pa-accent); text-decoration-thickness: 1px; text-underline-offset: 0.18em; }
        a:hover { color: var(--pa-accent-hover); text-decoration-thickness: 2px; }

        /* One focus treatment everywhere: an accent ring with a contrasting spacer so it stays
           visible on tinted surfaces, inside cards and on top of the accent colour itself. */
        a:focus-visible, button:focus-visible, input:focus-visible, select:focus-visible, textarea:focus-visible, summary:focus-visible, [tabindex]:focus-visible, details:focus-visible {
          outline: 2px solid var(--pa-focus);
          outline-offset: 2px;
          box-shadow: 0 0 0 2px var(--pa-focus-contrast);
        }

        ::selection { background: var(--pa-accent-soft); color: var(--pa-text); }

        .visually-hidden { position: absolute !important; width: 1px !important; height: 1px !important; padding: 0 !important; margin: -1px !important; overflow: hidden !important; clip: rect(0, 0, 0, 0) !important; white-space: nowrap !important; border: 0 !important; }

        /* ------------------------------------------------------------------ brand */

        .brand {
          display: inline-flex;
          align-items: center;
          gap: 0.4375rem;
          color: var(--pa-text);
          font-family: var(--pa-font-display);
          font-size: var(--pa-t-md);
          font-weight: 600;
          letter-spacing: -0.012em;
          text-decoration: none;
          white-space: nowrap;
        }

        .brand:hover { color: var(--pa-text); text-decoration: none; }
        .brand-mark { display: block; flex: 0 0 auto; width: 1.25rem; height: 1.25rem; color: var(--pa-accent); }
        .brand-qualifier { color: var(--pa-text-3); font-size: var(--pa-t-xs); font-weight: 500; letter-spacing: 0; }
        .brand-qualifier::before { margin-right: 0.4375rem; color: var(--pa-line-strong); content: "/"; }

        /* Small-caps micro-label for section kickers and group labels, never for body copy. */
        .eyebrow {
          margin: 0;
          color: var(--pa-text-3);
          font-family: var(--pa-font-sans);
          font-size: var(--pa-t-3xs);
          font-weight: 650;
          letter-spacing: 0.09em;
          text-transform: uppercase;
        }

        /* --------------------------------------------------------------- controls */

        /* Shared control geometry. Each surface sets its own default emphasis: the application leads
           with a filled primary action, the report is mostly utility controls on a quiet ground. */
        button, .button-link, .secondary-button {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          gap: 0.375rem;
          min-height: 2.125rem;
          padding: 0.3125rem 0.75rem;
          border: 1px solid var(--pa-line-strong);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          color: var(--pa-text);
          font: inherit;
          font-size: var(--pa-t-sm);
          font-weight: 600;
          line-height: 1.35;
          text-decoration: none;
          cursor: pointer;
          transition: background var(--pa-fast) var(--pa-ease), border-color var(--pa-fast) var(--pa-ease), color var(--pa-fast) var(--pa-ease);
        }

        button:hover, .secondary-button:hover {
          border-color: var(--pa-accent-line);
          background: var(--pa-accent-soft);
          color: var(--pa-accent-hover);
        }

        button:disabled { opacity: 0.55; cursor: not-allowed; }
        button:disabled:hover { border-color: var(--pa-line-strong); background: var(--pa-surface); color: var(--pa-text); }

        input, select, textarea {
          width: 100%;
          min-height: 2.125rem;
          padding: 0.3125rem 0.5rem;
          border: 1px solid var(--pa-line-strong);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          color: var(--pa-text);
          font: inherit;
          font-size: var(--pa-t-sm);
          transition: border-color var(--pa-fast) var(--pa-ease);
        }

        input::placeholder { color: var(--pa-text-3); }
        input:hover, select:hover { border-color: var(--pa-text-3); }
        input[type="checkbox"], input[type="radio"] { width: auto; min-height: 0; accent-color: var(--pa-accent); }

        /* Segmented System / Light / Dark control, identical in both surfaces. */
        .appearance-control {
          display: inline-flex;
          align-items: center;
          gap: 1px;
          padding: 2px;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface-2);
        }

        .appearance-option {
          display: inline-grid;
          min-height: 0;
          width: 1.75rem;
          height: 1.5rem;
          place-items: center;
          padding: 0;
          border: 0;
          border-radius: var(--pa-r1);
          background: transparent;
          color: var(--pa-text-3);
        }

        .appearance-option:hover { background: transparent; border-color: transparent; color: var(--pa-text); }
        .appearance-option[aria-pressed="true"] { background: var(--pa-surface); color: var(--pa-text); box-shadow: var(--pa-shadow-1); }
        .appearance-option::before { width: 0.9375rem; height: 0.9375rem; background: currentColor; content: ""; }
        .appearance-option[data-appearance="system"]::before { mask: var(--pa-icon-system) center / contain no-repeat; -webkit-mask: var(--pa-icon-system) center / contain no-repeat; }
        .appearance-option[data-appearance="light"]::before { mask: var(--pa-icon-light) center / contain no-repeat; -webkit-mask: var(--pa-icon-light) center / contain no-repeat; }
        .appearance-option[data-appearance="dark"]::before { mask: var(--pa-icon-dark) center / contain no-repeat; -webkit-mask: var(--pa-icon-dark) center / contain no-repeat; }

        /* ----------------------------------------------------------------- badges */

        /* Every classification reads as glyph + label + hue. The glyph and the label carry the meaning
           on their own; the hue only makes scanning faster. Solid outlines mean evidence was found,
           dashed outlines mean none was. */
        .badge {
          display: inline-flex;
          max-width: 100%;
          flex: 0 0 auto;
          align-items: center;
          gap: 0.3125rem;
          padding: 0.0625rem 0.375rem 0.0625rem 0.3125rem;
          border: 1px solid var(--pa-badge-line, var(--pa-neutral-line));
          border-radius: var(--pa-r1);
          background: var(--pa-badge-soft, var(--pa-neutral-soft));
          color: var(--pa-badge-fg, var(--pa-neutral));
          font-size: var(--pa-t-2xs);
          font-weight: 600;
          line-height: 1.5;
          white-space: nowrap;
        }

        .badge::before {
          width: 0.75rem;
          height: 0.75rem;
          flex: 0 0 auto;
          background: currentColor;
          content: "";
          mask: var(--pa-badge-glyph, none) center / contain no-repeat;
          -webkit-mask: var(--pa-badge-glyph, none) center / contain no-repeat;
        }

        .badge-neutral::before { display: none; }

        .badge-error { --pa-badge-fg: var(--pa-error); --pa-badge-soft: var(--pa-error-soft); --pa-badge-line: var(--pa-error-line); --pa-badge-glyph: var(--pa-icon-error); }
        .badge-warning { --pa-badge-fg: var(--pa-warning); --pa-badge-soft: var(--pa-warning-soft); --pa-badge-line: var(--pa-warning-line); --pa-badge-glyph: var(--pa-icon-warning); }
        .badge-review { --pa-badge-fg: var(--pa-review); --pa-badge-soft: var(--pa-review-soft); --pa-badge-line: var(--pa-review-line); --pa-badge-glyph: var(--pa-icon-review); }
        .badge-information { --pa-badge-fg: var(--pa-info); --pa-badge-soft: var(--pa-info-soft); --pa-badge-line: var(--pa-info-line); --pa-badge-glyph: var(--pa-icon-info); }
        .badge-neutral { --pa-badge-fg: var(--pa-neutral); --pa-badge-soft: var(--pa-neutral-soft); --pa-badge-line: var(--pa-neutral-line); }

        .badge-used { --pa-badge-fg: var(--pa-used); --pa-badge-soft: var(--pa-used-soft); --pa-badge-line: var(--pa-used-line); --pa-badge-glyph: var(--pa-icon-used); }
        .badge-indirect { --pa-badge-fg: var(--pa-indirect); --pa-badge-soft: var(--pa-indirect-soft); --pa-badge-line: var(--pa-indirect-line); --pa-badge-glyph: var(--pa-icon-indirect); }
        .badge-structural { --pa-badge-fg: var(--pa-structural); --pa-badge-soft: var(--pa-structural-soft); --pa-badge-line: var(--pa-structural-line); --pa-badge-glyph: var(--pa-icon-structural); }
        .badge-unused-branch { --pa-badge-fg: var(--pa-branch); --pa-badge-soft: var(--pa-branch-soft); --pa-badge-line: var(--pa-branch-line); --pa-badge-glyph: var(--pa-icon-branch); border-style: dashed; }
        .badge-unused { --pa-badge-fg: var(--pa-unused); --pa-badge-soft: var(--pa-unused-soft); --pa-badge-line: var(--pa-unused-line); --pa-badge-glyph: var(--pa-icon-unused); border-style: dashed; }

        /* ---------------------------------------------------------------- metrics */

        /* Counts print on a hairline-divided rail rather than in boxes: the same information in roughly
           half the vertical space, and the eye reads a row of numbers instead of a row of cards. */
        .metrics {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(8rem, 1fr));
          margin: 0;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          overflow: clip;
        }

        .metric {
          min-width: 0;
          margin: 0;
          padding: 0.5rem 0.75rem 0.625rem;
          border-left: 1px solid var(--pa-line);
        }

        .metric:first-child { border-left: 0; }

        .metric dt, .metric > span {
          display: flex;
          align-items: center;
          gap: 0.3125rem;
          color: var(--pa-text-2);
          font-size: var(--pa-t-2xs);
          font-weight: 550;
          overflow-wrap: anywhere;
        }

        .metric dd, .metric > strong {
          display: block;
          margin: 0.0625rem 0 0;
          color: var(--pa-text);
          font-family: var(--pa-font-display);
          font-size: var(--pa-t-xl);
          font-weight: 600;
          font-variant-numeric: tabular-nums;
          letter-spacing: -0.02em;
          line-height: 1.15;
        }

        /* The state dot repeats the badge glyph vocabulary at label size, so a count and a classification
           are recognisably the same thing. */
        .metric-error, .metric-warning, .metric-review, .metric-used, .metric-indirect, .metric-structural, .metric-branch, .metric-unused {
          --pa-metric-fg: var(--pa-neutral);
        }

        .metric-error dt::before, .metric-error > span::before,
        .metric-warning dt::before, .metric-warning > span::before,
        .metric-review dt::before, .metric-review > span::before,
        .metric-used dt::before, .metric-used > span::before,
        .metric-indirect dt::before, .metric-indirect > span::before,
        .metric-structural dt::before, .metric-structural > span::before,
        .metric-branch dt::before, .metric-branch > span::before,
        .metric-unused dt::before, .metric-unused > span::before {
          width: 0.6875rem;
          height: 0.6875rem;
          flex: 0 0 auto;
          background: var(--pa-metric-fg);
          content: "";
          mask: var(--pa-metric-glyph, none) center / contain no-repeat;
          -webkit-mask: var(--pa-metric-glyph, none) center / contain no-repeat;
        }

        .metric-error { --pa-metric-fg: var(--pa-error); --pa-metric-glyph: var(--pa-icon-error); }
        .metric-warning { --pa-metric-fg: var(--pa-warning); --pa-metric-glyph: var(--pa-icon-warning); }
        .metric-review { --pa-metric-fg: var(--pa-review); --pa-metric-glyph: var(--pa-icon-review); }
        .metric-used { --pa-metric-fg: var(--pa-used); --pa-metric-glyph: var(--pa-icon-used); }
        .metric-indirect { --pa-metric-fg: var(--pa-indirect); --pa-metric-glyph: var(--pa-icon-indirect); }
        .metric-structural { --pa-metric-fg: var(--pa-structural); --pa-metric-glyph: var(--pa-icon-structural); }
        .metric-branch { --pa-metric-fg: var(--pa-branch); --pa-metric-glyph: var(--pa-icon-branch); }
        .metric-unused { --pa-metric-fg: var(--pa-unused); --pa-metric-glyph: var(--pa-icon-unused); }

        /* --------------------------------------------------------------- notices */

        .notice {
          display: grid;
          gap: 0.1875rem;
          padding: 0.625rem 0.75rem;
          border: 1px solid var(--pa-notice-line, var(--pa-line));
          border-left: 3px solid var(--pa-notice-fg, var(--pa-text-3));
          border-radius: var(--pa-r2);
          background: var(--pa-notice-soft, var(--pa-surface-2));
          overflow-wrap: anywhere;
        }

        .notice > :first-child { margin-top: 0; }
        .notice > :last-child { margin-bottom: 0; }
        .notice-info { --pa-notice-fg: var(--pa-info); --pa-notice-soft: var(--pa-info-soft); --pa-notice-line: var(--pa-info-line); }
        .notice-warning { --pa-notice-fg: var(--pa-warning); --pa-notice-soft: var(--pa-warning-soft); --pa-notice-line: var(--pa-warning-line); }
        .notice-review { --pa-notice-fg: var(--pa-review); --pa-notice-soft: var(--pa-review-soft); --pa-notice-line: var(--pa-review-line); }
        .notice-caution { --pa-notice-fg: var(--pa-unused); --pa-notice-soft: var(--pa-unused-soft); --pa-notice-line: var(--pa-unused-line); }
        .notice-success { --pa-notice-fg: var(--pa-used); --pa-notice-soft: var(--pa-used-soft); --pa-notice-line: var(--pa-used-line); }

        /* ------------------------------------------------------------- disclosure */

        /* A chevron that rotates, rather than a plus turning into a minus. */
        summary { cursor: pointer; color: var(--pa-accent); font-weight: 600; list-style: none; }
        summary::-webkit-details-marker { display: none; }
        summary:hover { color: var(--pa-accent-hover); }

        .disclosure-marker::after {
          width: 0.875rem;
          height: 0.875rem;
          flex: 0 0 auto;
          align-self: center;
          background: currentColor;
          content: "";
          mask: var(--pa-icon-chevron) center / contain no-repeat;
          -webkit-mask: var(--pa-icon-chevron) center / contain no-repeat;
          opacity: 0.7;
          transition: transform var(--pa-fast) var(--pa-ease);
        }

        [open] > .disclosure-marker::after { transform: rotate(90deg); }

        /* ------------------------------------------------------------------ icons */

        /* Monochrome masks so every glyph inherits the surrounding text colour and works unchanged in
           both themes. A failed mask loses the glyph, never the label. */
        :root {
          --pa-icon-error: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 1.25a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5Zm2.53 8.22a.75.75 0 1 1-1.06 1.06L8 9.06l-1.47 1.47a.75.75 0 0 1-1.06-1.06L6.94 8 5.47 6.53a.75.75 0 0 1 1.06-1.06L8 6.94l1.47-1.47a.75.75 0 1 1 1.06 1.06L9.06 8Z'/%3E%3C/svg%3E");
          --pa-icon-warning: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M7.13 1.96a1 1 0 0 1 1.74 0l6.03 10.55a1 1 0 0 1-.87 1.49H1.97a1 1 0 0 1-.87-1.49ZM8 5.4a.75.75 0 0 0-.75.75v3a.75.75 0 0 0 1.5 0v-3A.75.75 0 0 0 8 5.4Zm0 5.1a.9.9 0 1 0 0 1.8.9.9 0 0 0 0-1.8Z'/%3E%3C/svg%3E");
          --pa-icon-review: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 2.5c-3.2 0-5.9 2.1-7.3 4.9a1.4 1.4 0 0 0 0 1.2C2.1 11.4 4.8 13.5 8 13.5s5.9-2.1 7.3-4.9a1.4 1.4 0 0 0 0-1.2C13.9 4.6 11.2 2.5 8 2.5Zm0 1.6a3.9 3.9 0 1 1 0 7.8 3.9 3.9 0 0 1 0-7.8Zm0 1.7a2.2 2.2 0 1 0 0 4.4 2.2 2.2 0 0 0 0-4.4Z'/%3E%3C/svg%3E");
          --pa-icon-info: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 1.25a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM8 3.6a.95.95 0 1 1 0 1.9.95.95 0 0 1 0-1.9Zm1.15 8.4h-2.3a.7.7 0 0 1 0-1.4h.45V8.05h-.35a.7.7 0 1 1 0-1.4h1.05a.7.7 0 0 1 .7.7v3.25h.45a.7.7 0 1 1 0 1.4Z'/%3E%3C/svg%3E");
          --pa-icon-used: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Ccircle cx='8' cy='8' r='5.5'/%3E%3C/svg%3E");
          --pa-icon-indirect: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 1.6a6.4 6.4 0 1 0 0 12.8A6.4 6.4 0 0 0 8 1.6Zm0 1.5a4.9 4.9 0 1 1 0 9.8 4.9 4.9 0 0 1 0-9.8Z'/%3E%3Ccircle cx='8' cy='8' r='2.7'/%3E%3C/svg%3E");
          --pa-icon-structural: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M3.3 2.5h9.4c.44 0 .8.36.8.8v9.4c0 .44-.36.8-.8.8H3.3a.8.8 0 0 1-.8-.8V3.3c0-.44.36-.8.8-.8Zm.7 1.5v8h8V4Z'/%3E%3Cpath d='M6.2 6.2h3.6v3.6H6.2z'/%3E%3C/svg%3E");
          --pa-icon-branch: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 1.6a6.4 6.4 0 1 0 0 12.8A6.4 6.4 0 0 0 8 1.6Zm0 1.5a4.9 4.9 0 1 1 0 9.8 4.9 4.9 0 0 1 0-9.8Z'/%3E%3Cpath d='M8 3.9a4.1 4.1 0 0 0 0 8.2Z'/%3E%3C/svg%3E");
          --pa-icon-unused: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 1.6a6.4 6.4 0 1 0 0 12.8A6.4 6.4 0 0 0 8 1.6Zm0 1.6a4.8 4.8 0 1 1 0 9.6 4.8 4.8 0 0 1 0-9.6Z'/%3E%3C/svg%3E");
          --pa-icon-chevron: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M5.97 3.47a.75.75 0 0 1 1.06 0l4 4a.75.75 0 0 1 0 1.06l-4 4a.75.75 0 0 1-1.06-1.06L9.44 8 5.97 4.53a.75.75 0 0 1 0-1.06Z'/%3E%3C/svg%3E");
          --pa-icon-system: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M2.5 2.6h11c.5 0 .9.4.9.9v7c0 .5-.4.9-.9.9H9.1v1.1h1.6a.7.7 0 0 1 0 1.4H5.3a.7.7 0 0 1 0-1.4h1.6v-1.1H2.5a.9.9 0 0 1-.9-.9v-7c0-.5.4-.9.9-.9Zm.5 1.4v6h10v-6Z'/%3E%3C/svg%3E");
          --pa-icon-light: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Ccircle cx='8' cy='8' r='3.1'/%3E%3Cpath d='M8 .9a.7.7 0 0 1 .7.7v1.2a.7.7 0 1 1-1.4 0V1.6A.7.7 0 0 1 8 .9Zm0 11.3a.7.7 0 0 1 .7.7v1.2a.7.7 0 1 1-1.4 0v-1.2a.7.7 0 0 1 .7-.7ZM15.1 8a.7.7 0 0 1-.7.7h-1.2a.7.7 0 1 1 0-1.4h1.2a.7.7 0 0 1 .7.7ZM3.8 8a.7.7 0 0 1-.7.7H1.9a.7.7 0 0 1 0-1.4h1.2A.7.7 0 0 1 3.8 8Zm9.22-5.02a.7.7 0 0 1 0 .99l-.85.85a.7.7 0 1 1-.99-.99l.85-.85a.7.7 0 0 1 .99 0ZM4.82 11.18a.7.7 0 0 1 0 .99l-.85.85a.7.7 0 1 1-.99-.99l.85-.85a.7.7 0 0 1 .99 0Zm8.2 1.84a.7.7 0 0 1-.99 0l-.85-.85a.7.7 0 1 1 .99-.99l.85.85a.7.7 0 0 1 0 .99ZM4.82 4.82a.7.7 0 0 1-.99 0l-.85-.85a.7.7 0 0 1 .99-.99l.85.85a.7.7 0 0 1 0 .99Z'/%3E%3C/svg%3E");
          --pa-icon-dark: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M6.4 1.7a6.6 6.6 0 1 0 7.9 8.8 5.4 5.4 0 0 1-7.9-6.5 6.9 6.9 0 0 1 0-2.3Z'/%3E%3C/svg%3E");
        }

        /* ----------------------------------------------------------------- motion */

        @media (prefers-reduced-motion: reduce) {
          *, *::before, *::after {
            animation-duration: 0.01ms !important;
            animation-iteration-count: 1 !important;
            transition-duration: 0.01ms !important;
            scroll-behavior: auto !important;
          }
        }
        """;

    /// <summary>Presentation for the generated report, layered on top of <see cref="Core"/>.</summary>
    public const string Report = """
        /* PBI Assure generated report — presentation layer on top of the shared design system.
           Edit this file, then run: node scripts/Sync-DesignTokens.mjs
           The report is the denser expression of the product: the same tokens, controls and status
           vocabulary as the application, on a tighter spacing rhythm and a two-column workspace. */

        html { scroll-behavior: smooth; }

        body { font-size: var(--pa-t-sm); }

        h1 { margin: 0; font-size: var(--pa-t-2xl); }
        h2 { margin: 0 0 0.375rem; font-size: var(--pa-t-xl); }
        h3 { margin: 1.5rem 0 0.5rem; font-size: var(--pa-t-lg); }
        h4 { margin: 1rem 0 0.375rem; font-size: var(--pa-t-md); }
        h5, h6 { margin: 0.75rem 0 0.25rem; font-size: var(--pa-t-sm); }

        p { margin: 0 0 0.5rem; }

        .content { width: min(94rem, calc(100% - 2.5rem)); margin-inline: auto; }
        .report-content, .section-navigator { min-width: 0; }

        .skip-link {
          position: absolute;
          left: 0.75rem;
          top: -5rem;
          z-index: 20;
          padding: 0.5rem 0.875rem;
          border-radius: var(--pa-r2);
          background: var(--pa-accent);
          color: var(--pa-on-accent);
          font-weight: 600;
          text-decoration: none;
        }

        .skip-link:focus { top: 0.75rem; }

        /* ------------------------------------------------------------------ header */

        /* A compact product bar, not a report cover. The brand and the appearance control sit on one
           quiet line; the project identity and scan metadata sit beneath it in a single tight block. */
        .site-header {
          border-bottom: 1px solid var(--pa-line);
          background: var(--pa-surface);
        }

        .site-header-bar {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 1rem;
          min-height: 2.75rem;
          padding-block: 0.375rem;
          border-bottom: 1px solid var(--pa-line);
        }

        .site-header-identity { padding: 0.75rem 0 0.875rem; }
        .site-header .eyebrow { margin-bottom: 0.1875rem; }
        .site-header h1 { overflow-wrap: anywhere; }

        .lede { max-width: 68ch; margin: 0.25rem 0 0; color: var(--pa-text-2); font-size: var(--pa-t-xs); }

        .report-meta {
          display: flex;
          flex-wrap: wrap;
          gap: 0.125rem 1.25rem;
          margin: 0.625rem 0 0;
          padding: 0;
          font-size: var(--pa-t-2xs);
        }

        .report-meta div { display: flex; min-width: 0; max-width: 100%; flex-wrap: wrap; gap: 0.375rem; }
        .report-meta dt { color: var(--pa-text-3); font-weight: 600; }
        .report-meta dd { min-width: 0; margin: 0; color: var(--pa-text-2); font-family: var(--pa-font-mono); font-size: 0.95em; overflow-wrap: anywhere; }

        /* ------------------------------------------------------------- navigation */

        .section-nav {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(min(100%, 11rem), 1fr));
          gap: 0.375rem;
          margin: 1rem 0 0;
          padding: 0;
          list-style: none;
        }

        .section-nav a {
          display: grid;
          min-width: 0;
          align-content: center;
          gap: 0.0625rem;
          padding: 0.4375rem 0.625rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          color: var(--pa-text-2);
          font-size: var(--pa-t-xs);
          text-decoration: none;
          transition: background var(--pa-fast) var(--pa-ease), color var(--pa-fast) var(--pa-ease), border-color var(--pa-fast) var(--pa-ease);
        }

        .section-nav a > span { display: flex; align-items: center; gap: 0.4375rem; font-weight: 600; }
        .section-nav small { color: var(--pa-text-3); font-size: var(--pa-t-2xs); overflow-wrap: anywhere; }
        .section-nav a:hover { border-color: var(--pa-line-strong); background: var(--pa-surface-2); color: var(--pa-text); }
        .section-nav a[aria-current="page"] { border-color: var(--pa-accent-line); background: var(--pa-accent-soft); color: var(--pa-accent); }
        .section-nav a[aria-current="page"] small { color: inherit; opacity: 0.85; }

        /* Section identity glyphs. They repeat between the rail and the section heading so a reader
           who has learned one recognises the other. */
        .section-nav a > span::before {
          width: 0.9375rem;
          height: 0.9375rem;
          flex: 0 0 auto;
          background: currentColor;
          content: "";
          opacity: 0.9;
          mask: var(--pa-section-glyph, none) center / contain no-repeat;
          -webkit-mask: var(--pa-section-glyph, none) center / contain no-repeat;
        }

        .section-nav a[href="#summary"] { --pa-section-glyph: var(--pa-icon-summary); }
        .section-nav a[href="#semantic-usage"] { --pa-section-glyph: var(--pa-icon-model); }
        .section-nav a[href="#power-query"] { --pa-section-glyph: var(--pa-icon-query); }
        .section-nav a[href="#relationships"] { --pa-section-glyph: var(--pa-icon-relationship); }
        .section-nav a[href="#row-level-security"] { --pa-section-glyph: var(--pa-icon-security); }
        .section-nav a[href="#reports"] { --pa-section-glyph: var(--pa-icon-pages); }
        .section-nav a[href="#findings"] { --pa-section-glyph: var(--pa-icon-findings); }
        .section-nav a[href="#analysis-coverage"] { --pa-section-glyph: var(--pa-icon-coverage); }
        .section-nav a[href="#theme-review"] { --pa-section-glyph: var(--pa-icon-theme); }
        .section-nav a[href="#accessibility-review"] { --pa-section-glyph: var(--pa-icon-accessibility); }

        /* --------------------------------------------------------------- sections */

        /* Sections are delimited by their heading and the space around them. Wrapping each one in a
           card produced a card inside a card inside a card and cost a great deal of vertical space. */
        main > section { min-width: 0; margin: 1.5rem 0 2.5rem; }
        main > section > h2 { scroll-margin-top: 1rem; }
        .section-intro { max-width: 78ch; margin: 0 0 1rem; color: var(--pa-text-2); }
        .group-explanation { max-width: 74ch; margin: 0 0 0.5rem; color: var(--pa-text-2); font-size: var(--pa-t-xs); }

        .summary-groups { display: grid; min-width: 0; gap: 1.5rem; }
        .summary-group { min-width: 0; }

        .summary-group > h3 {
          display: flex;
          align-items: center;
          gap: 0.625rem;
          margin: 0 0 0.375rem;
          color: var(--pa-text-3);
          font-family: var(--pa-font-sans);
          font-size: var(--pa-t-3xs);
          font-weight: 650;
          letter-spacing: 0.09em;
          text-transform: uppercase;
        }

        .summary-group > h3::after { height: 1px; flex: 1; background: var(--pa-line); content: ""; }

        .summary-note { margin: 1.25rem 0 0.25rem; color: var(--pa-text-2); }
        .secondary, .filter-status { color: var(--pa-text-2); }
        .summary-coverage-note { max-width: 74ch; margin: 0.5rem 0 0; color: var(--pa-text-2); font-size: var(--pa-t-xs); }

        .section-empty-state {
          display: grid;
          max-width: 78ch;
          gap: 0.125rem;
          margin: 0.75rem 0;
          padding: 0.625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-left: 3px solid var(--pa-text-3);
          border-radius: var(--pa-r2);
          background: var(--pa-surface-2);
          overflow-wrap: anywhere;
        }

        .section-empty-state span { color: var(--pa-text-2); font-size: var(--pa-t-xs); }
        .section-empty-success { border-left-color: var(--pa-used); background: var(--pa-used-soft); border-color: var(--pa-used-line); }
        .section-empty-unavailable { border-left-color: var(--pa-info); background: var(--pa-info-soft); border-color: var(--pa-info-line); }

        /* The caution belongs to the "apparently unused" state, so it borrows that hue for its edge and
           nothing else. A full tinted panel here shouted louder than the counts it is annotating. */
        .summary-caution {
          max-width: 78ch;
          margin: 0.625rem 0 0;
          padding: 0.5rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-left: 3px solid var(--pa-unused);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          font-size: var(--pa-t-xs);
          overflow-wrap: anywhere;
        }

        .summary-caution strong { color: var(--pa-unused); }

        /* --------------------------------------------------------------- metrics */

        .metrics { margin: 0; }
        .summary-group .metric dd { font-size: var(--pa-t-xl); }
        .theme-metrics { margin-bottom: 1rem; }

        /* --------------------------------------------------------- disclosures */

        details { margin-top: 0.5rem; }

        .summary-definitions, .section-help {
          margin-top: 0.625rem;
          padding: 0.4375rem 0.625rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
        }

        .summary-definitions > summary, .section-help > summary { display: flex; align-items: center; gap: 0.4375rem; font-size: var(--pa-t-xs); }
        .summary-definitions dl { display: grid; gap: 0.5rem; margin: 0.625rem 0 0.125rem; }
        .summary-definitions dl div { display: grid; gap: 0.0625rem; }
        .summary-definitions dt { color: var(--pa-text); font-size: var(--pa-t-xs); font-weight: 650; }
        .summary-definitions dd { margin: 0; color: var(--pa-text-2); font-size: var(--pa-t-xs); overflow-wrap: anywhere; }
        .section-help > p { max-width: 78ch; margin: 0.5rem 0 0.125rem; color: var(--pa-text-2); font-size: var(--pa-t-xs); }
        .section-help > ul { margin: 0.5rem 0 0.125rem; color: var(--pa-text-2); font-size: var(--pa-t-xs); }

        .scope { border-left: 3px solid var(--pa-warning) !important; background: var(--pa-warning-soft) !important; border-color: var(--pa-warning-line) !important; }
        .scope > summary { color: var(--pa-warning); }

        /* ------------------------------------------------------- analysis coverage */

        .coverage-model { min-width: 0; margin: 0 0 1.25rem; }
        .coverage-model + .coverage-model { padding-top: 1rem; border-top: 1px solid var(--pa-line); }
        .coverage-model h3 { margin: 0.375rem 0 0.25rem; font-size: var(--pa-t-md); }
        .coverage-headline { max-width: 78ch; margin: 0.25rem 0 0.625rem; overflow-wrap: anywhere; }
        .coverage-list { display: grid; min-width: 0; gap: 0.5rem; margin: 0 0 0.625rem; padding: 0; list-style: none; }

        .coverage-item {
          min-width: 0;
          padding: 0.5625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-left: 3px solid var(--pa-text-3);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          overflow-wrap: anywhere;
        }

        .coverage-item-qualifying { border-color: var(--pa-info-line); border-left-color: var(--pa-info); background: var(--pa-info-soft); }
        .coverage-item p { margin: 0; }
        .coverage-item-head { display: flex; flex-wrap: wrap; align-items: center; gap: 0.3125rem 0.5rem; }
        .coverage-impact { color: var(--pa-text-3); font-size: var(--pa-t-2xs); font-weight: 650; }
        .coverage-item-qualifying .coverage-impact { color: var(--pa-info); }
        .coverage-reason { margin-top: 0.3125rem !important; max-width: 74ch; color: var(--pa-text-2); font-size: var(--pa-t-xs); }
        .coverage-artifacts { margin-top: 0.375rem !important; color: var(--pa-text-3); font-size: var(--pa-t-2xs); }
        .coverage-other { margin: 0; }

        .coverage-other > summary {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          padding: 0.4375rem 0.625rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          font-size: var(--pa-t-xs);
        }

        .coverage-other > summary::after {
          width: 0.875rem;
          height: 0.875rem;
          margin-left: auto;
          background: currentColor;
          content: "";
          mask: var(--pa-icon-chevron) center / contain no-repeat;
          -webkit-mask: var(--pa-icon-chevron) center / contain no-repeat;
          transition: transform var(--pa-fast) var(--pa-ease);
        }

        .coverage-other[open] > summary::after { transform: rotate(90deg); }
        .coverage-other > summary:hover { border-color: var(--pa-accent-line); background: var(--pa-accent-soft); }
        .coverage-other[open] > summary { margin-bottom: 0.5rem; }
        .coverage-footnote { max-width: 78ch; margin: 0.5rem 0 0; color: var(--pa-text-3); font-size: var(--pa-t-2xs); }
        .usage-guide-note { max-width: 78ch; margin: 0.75rem 0 0; padding-top: 0.625rem; border-top: 1px solid var(--pa-line); color: var(--pa-text-2); font-size: var(--pa-t-xs); }

        .confidence-flag {
          align-self: center;
          padding: 0.0625rem 0.375rem;
          border: 1px dashed var(--pa-line-strong);
          border-radius: var(--pa-r1);
          color: var(--pa-text-2);
          font-size: var(--pa-t-2xs);
          font-weight: 600;
          text-decoration: none;
          white-space: nowrap;
        }

        a.confidence-flag:hover { border-style: solid; border-color: var(--pa-accent-line); background: var(--pa-accent-soft); color: var(--pa-accent); }
        .confidence-flag-sample { display: inline-block; vertical-align: baseline; }

        /* ------------------------------------------------------------------ cards */

        /* Cards are reserved for discrete objects a reader can open: a finding, a model table, a page,
           a visual, a query, a relationship, a role. Nothing else gets a border. */
        .card-list, .page-list, .relationship-list, .semantic-table-list, .visual-list {
          display: grid;
          min-width: 0;
          grid-template-columns: minmax(0, 1fr);
          gap: 0.5rem;
        }

        .finding-card, .accessibility-finding-card, .page-card, .relationship-card, .visual-card, .semantic-table, .rls-role-card, .theme-visual-card, .power-query-card {
          min-width: 0;
          max-width: 100%;
          margin: 0;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          overflow: clip;
          transition: border-color var(--pa-fast) var(--pa-ease);
        }

        .finding-card:hover, .accessibility-finding-card:hover, .page-card:hover, .relationship-card:hover, .semantic-table:hover, .rls-role-card:hover, .theme-visual-card:hover, .power-query-card:hover { border-color: var(--pa-line-strong); }
        .visual-card { background: var(--pa-surface-2); }

        .finding-card > summary, .accessibility-finding-card > summary, .page-card > summary, .relationship-card > summary, .visual-card > summary, .semantic-table > summary, .rls-role-card > summary, .theme-visual-card > summary, .power-query-card > summary {
          display: flex;
          align-items: flex-start;
          justify-content: space-between;
          gap: 0.75rem;
          padding: 0.5625rem 0.75rem;
          color: var(--pa-text);
          font-weight: 500;
          transition: background var(--pa-fast) var(--pa-ease);
        }

        .finding-card > summary:hover, .accessibility-finding-card > summary:hover, .page-card > summary:hover, .relationship-card > summary:hover, .visual-card > summary:hover, .semantic-table > summary:hover, .rls-role-card > summary:hover, .theme-visual-card > summary:hover, .power-query-card > summary:hover {
          background: var(--pa-surface-2);
          color: var(--pa-text);
        }

        .finding-card > summary::after, .accessibility-finding-card > summary::after, .page-card > summary::after, .relationship-card > summary::after, .visual-card > summary::after, .semantic-table > summary::after, .rls-role-card > summary::after, .theme-visual-card > summary::after, .power-query-card > summary::after {
          width: 0.875rem;
          height: 0.875rem;
          flex: 0 0 auto;
          align-self: center;
          background: var(--pa-text-3);
          content: "";
          mask: var(--pa-icon-chevron) center / contain no-repeat;
          -webkit-mask: var(--pa-icon-chevron) center / contain no-repeat;
          transition: transform var(--pa-fast) var(--pa-ease);
        }

        .finding-card[open] > summary::after, .accessibility-finding-card[open] > summary::after, .page-card[open] > summary::after, .relationship-card[open] > summary::after, .visual-card[open] > summary::after, .semantic-table[open] > summary::after, .rls-role-card[open] > summary::after, .theme-visual-card[open] > summary::after, .power-query-card[open] > summary::after {
          transform: rotate(90deg);
        }

        .finding-card[open] > summary, .accessibility-finding-card[open] > summary, .page-card[open] > summary, .relationship-card[open] > summary, .visual-card[open] > summary, .semantic-table[open] > summary, .rls-role-card[open] > summary, .theme-visual-card[open] > summary, .power-query-card[open] > summary {
          border-bottom: 1px solid var(--pa-line);
        }

        .finding-card > summary, .accessibility-finding-card > summary { justify-content: flex-start; }
        .page-card > summary { padding: 0.6875rem 0.875rem; background: var(--pa-surface-2); }
        .page-card[open] > summary { background: var(--pa-surface-2); }
        .rls-role-card > summary, .power-query-card > summary { align-items: center; }

        /* Severity is carried by a full-height edge on the card as well as by the badge in its summary. */
        .finding-card[data-severity="Error"], .accessibility-finding-card[data-severity="Error"] { border-left: 3px solid var(--pa-error); }
        .finding-card[data-severity="Warning"], .accessibility-finding-card[data-severity="Warning"] { border-left: 3px solid var(--pa-warning); }
        .finding-card[data-severity="Information"], .accessibility-finding-card[data-severity="Information"] { border-left: 3px solid var(--pa-info); }

        .summary-copy { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 0.0625rem; overflow-wrap: anywhere; }
        .summary-copy > strong, .visual-name > strong { color: var(--pa-text); font-size: var(--pa-t-md); font-weight: 600; letter-spacing: -0.008em; }
        .summary-copy > span:not(.kicker), .visual-name .secondary { color: var(--pa-text-2); font-size: var(--pa-t-xs); font-weight: 400; }
        .summary-metadata { display: flex; min-width: 0; flex-wrap: wrap; gap: 0.0625rem 0.3125rem; font-size: var(--pa-t-xs); }
        .summary-metadata > span { min-width: 0; overflow-wrap: anywhere; }
        .summary-metadata > span:not(:last-child)::after { color: var(--pa-text-3); content: " ·"; font-weight: 400; }
        .summary-metadata strong { color: var(--pa-text); font-weight: 600; }
        .finding-card .summary-metadata strong, .accessibility-finding-card .summary-metadata strong, .page-card .summary-metadata strong { color: inherit; font-weight: 600; }

        .kicker { color: var(--pa-text-3); font-size: var(--pa-t-3xs); font-weight: 650; letter-spacing: 0.08em; text-transform: uppercase; }

        .count-pill {
          align-self: center;
          padding: 0.0625rem 0.375rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r1);
          background: var(--pa-surface-2);
          color: var(--pa-text-2);
          font-size: var(--pa-t-2xs);
          font-weight: 600;
          font-variant-numeric: tabular-nums;
          white-space: nowrap;
        }

        .card-body, .page-body, .visual-body { min-width: 0; max-width: 100%; padding: 0.75rem 0.875rem 0.875rem; }
        .card-body > :first-child, .page-body > :first-child, .visual-body > :first-child { margin-top: 0; }
        .card-body h3, .page-body h3, .visual-body h4 { margin: 1rem 0 0.375rem; font-size: var(--pa-t-sm); }
        .card-body > h3:first-child, .page-body > h3:first-child, .visual-body > h4:first-child { margin-top: 0; }

        /* --------------------------------------------------------------- fact grids */

        .fact-strip {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(9rem, 1fr));
          gap: 0;
          margin: 0 0 0.875rem;
          padding: 0;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface-2);
          overflow: clip;
        }

        .fact-strip div { padding: 0.4375rem 0.625rem; border-left: 1px solid var(--pa-line); }
        .fact-strip div:first-child { border-left: 0; }
        .fact-strip dt { display: flex; align-items: center; gap: 0.3125rem; color: var(--pa-text-3); font-size: var(--pa-t-2xs); font-weight: 600; }
        .fact-strip dd { margin: 0.0625rem 0 0; color: var(--pa-text); font-size: var(--pa-t-xs); font-weight: 600; overflow-wrap: anywhere; }
        .fact-strip.compact { grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr)); }
        .fact-primary, .fact-supporting { display: block; }
        .fact-supporting { margin-top: 0.0625rem; color: var(--pa-text-3); font-size: var(--pa-t-2xs); font-weight: 400; }

        .info-tooltip {
          position: relative;
          display: inline-grid;
          width: 1rem;
          height: 1rem;
          min-width: 1rem;
          min-height: 1rem;
          flex: 0 0 1rem;
          place-items: center;
          padding: 0;
          border: 1px solid var(--pa-line-strong);
          border-radius: 50%;
          background: transparent;
          color: var(--pa-text-3);
          font: 650 var(--pa-t-3xs)/1 var(--pa-font-sans);
          cursor: help;
        }

        .info-tooltip:hover { border-color: var(--pa-accent-line); background: var(--pa-accent-soft); color: var(--pa-accent); }

        .info-tooltip [role="tooltip"] {
          position: absolute;
          z-index: 5;
          top: calc(100% + 0.375rem);
          left: 0;
          width: max-content;
          max-width: min(20rem, 70vw);
          padding: 0.4375rem 0.5625rem;
          border: 1px solid var(--pa-line-strong);
          border-radius: var(--pa-r2);
          background: var(--pa-text);
          box-shadow: var(--pa-shadow-2);
          color: var(--pa-canvas);
          font-size: var(--pa-t-2xs);
          font-weight: 400;
          line-height: 1.4;
          text-align: left;
          opacity: 0;
          pointer-events: none;
          transition: opacity var(--pa-fast) var(--pa-ease);
        }

        .info-tooltip:hover [role="tooltip"], .info-tooltip:focus [role="tooltip"], .info-tooltip:focus-visible [role="tooltip"] { opacity: 1; }

        /* --------------------------------------------------------- search & filters */

        /* The investigation controls are one quiet toolbar, not a shaded panel competing with results. */
        .filters, .finding-investigation {
          display: flex;
          min-width: 0;
          flex-wrap: wrap;
          gap: 0.75rem 1rem;
          align-items: end;
          margin: 0.75rem 0 0.5rem;
          padding: 0.75rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
        }

        .finding-investigation { display: block; }
        .filters div { min-width: min(100%, 14rem); flex: 1; }
        .finding-search { max-width: 48rem; }
        .finding-filter-panel { min-width: 0; margin-top: 0.625rem; border-top: 1px solid var(--pa-line); }
        .finding-filter-panel > summary { display: flex; width: fit-content; align-items: center; gap: 0.4375rem; padding-top: 0.5625rem; font-size: var(--pa-t-xs); }

        .active-filter-count {
          padding: 0.0625rem 0.375rem;
          border-radius: 999px;
          background: var(--pa-accent);
          color: var(--pa-on-accent);
          font-size: var(--pa-t-3xs);
          font-variant-numeric: tabular-nums;
        }

        .finding-facet-grid { display: grid; min-width: 0; grid-template-columns: repeat(auto-fit, minmax(min(100%, 13rem), 1fr)); gap: 0.625rem 1rem; padding-top: 0.75rem; }
        .finding-facet-grid > div { min-width: 0; }
        .finding-results-row { display: flex; min-width: 0; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 0.5rem 1rem; margin: 0.75rem 0 0.375rem; }
        .finding-results-row .filter-status { margin: 0; font-size: var(--pa-t-xs); font-weight: 600; }
        .finding-results-row button { min-height: 1.875rem; padding: 0.1875rem 0.5rem; font-size: var(--pa-t-2xs); }
        .filter-chips { display: flex; min-width: 0; flex-wrap: wrap; gap: 0.375rem; margin: 0.3125rem 0 0.625rem; }
        .filter-chips[hidden], .finding-empty-state[hidden] { display: none; }

        .filter-chip {
          min-height: 1.75rem;
          max-width: 100%;
          padding: 0.125rem 0.5rem;
          border-radius: 999px;
          background: var(--pa-surface-2);
          font-size: var(--pa-t-2xs);
          font-weight: 500;
          overflow-wrap: anywhere;
        }

        .filter-chip::after { margin-left: 0.3125rem; content: "×"; font-size: 1.1em; }

        .finding-empty-state {
          display: grid;
          gap: 0.25rem;
          justify-items: start;
          margin: 0.75rem 0;
          padding: 1rem;
          border: 1px dashed var(--pa-line-strong);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
        }

        .finding-empty-state span { color: var(--pa-text-2); font-size: var(--pa-t-xs); }
        .finding-empty-state button { margin-top: 0.3125rem; }

        label { display: block; margin-bottom: 0.25rem; color: var(--pa-text-2); font-size: var(--pa-t-2xs); font-weight: 600; }
        .details-controls { display: flex; flex-wrap: wrap; gap: 0.375rem; margin: 0.75rem 0; }
        .details-controls button { min-height: 1.875rem; padding: 0.1875rem 0.625rem; font-size: var(--pa-t-2xs); }

        /* ------------------------------------------------------- rule catalogue */

        .rule-catalogue-hint { margin-left: 0.375rem; color: var(--pa-text-3); font-size: var(--pa-t-2xs); font-weight: 400; }
        .rule-category { min-width: 0; margin-top: 1rem; }
        .rule-category h3 { margin-bottom: 0.5rem; font-size: var(--pa-t-sm); }
        .rule-catalogue-list { display: grid; min-width: 0; grid-template-columns: repeat(auto-fit, minmax(min(100%, 19rem), 1fr)); gap: 0.5rem; }

        .rule-catalogue-item {
          display: flex;
          min-width: 0;
          flex-direction: column;
          align-items: flex-start;
          padding: 0.625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          overflow-wrap: anywhere;
        }

        .rule-catalogue-item h4 { margin: 0; font-size: var(--pa-t-xs); }
        .rule-catalogue-item p { margin: 0.25rem 0 0; color: var(--pa-text-2); font-size: var(--pa-t-xs); }
        .rule-finding-count { min-height: 0; margin-top: auto; padding: 0.375rem 0 0; border: 0; background: transparent; color: var(--pa-accent); font-size: var(--pa-t-xs); text-align: left; text-decoration: underline; }
        .rule-finding-count:hover { border: 0; background: transparent; color: var(--pa-accent-hover); text-decoration-thickness: 2px; }
        .rule-finding-count-empty { padding-top: 0.125rem; color: var(--pa-text-3); font-size: var(--pa-t-2xs); text-decoration: none; }

        /* ----------------------------------------------------------- accessibility */

        .accessibility-boundary, .theme-boundary, .rls-boundary, .theme-early-access {
          max-width: 78ch;
          margin: 0.75rem 0 1rem;
          padding: 0.625rem 0.75rem;
          border: 1px solid var(--pa-info-line);
          border-left: 3px solid var(--pa-info);
          border-radius: var(--pa-r2);
          background: var(--pa-info-soft);
          font-size: var(--pa-t-xs);
          overflow-wrap: anywhere;
        }

        .accessibility-boundary p, .theme-boundary p, .rls-boundary p, .theme-early-access p { margin: 0.25rem 0 0; }
        .accessibility-boundary > :first-child, .theme-boundary > :first-child, .rls-boundary > :first-child, .theme-early-access > :first-child { margin-top: 0; }
        .accessibility-summary { margin: 1.25rem 0; }
        .accessibility-summary h3 { margin-bottom: 0.25rem; }
        .accessibility-summary-list { display: grid; min-width: 0; grid-template-columns: repeat(auto-fit, minmax(min(100%, 17rem), 1fr)); gap: 0.5rem; margin-top: 0.75rem; }

        .accessibility-summary-card {
          min-width: 0;
          padding: 0.5625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          overflow-wrap: anywhere;
        }

        .accessibility-summary-card h4 { margin: 0; font-size: var(--pa-t-xs); }
        .accessibility-summary-card p { margin: 0.3125rem 0 0; font-size: var(--pa-t-xs); font-weight: 600; }

        /* --------------------------------------------------------- semantic model */

        .model-block + .model-block { margin-top: 2rem; }
        .model-block h3 { margin-bottom: 0.5rem; }
        .system-generated-table { border-style: dashed; background: var(--pa-surface-2); }
        .semantic-table[hidden], .semantic-object[hidden], .finding-card[hidden], .accessibility-finding-card[hidden], .page-card[hidden], .visual-card[hidden], .theme-visual-card[hidden], .theme-governance-card[hidden] { display: none; }

        .usage-guide {
          min-width: 0;
          max-width: 100%;
          margin: 0.75rem 0 1rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          overflow: clip;
        }

        .usage-guide > summary { display: flex; min-width: 0; align-items: center; justify-content: space-between; gap: 0.75rem; padding: 0.5625rem 0.75rem; font-size: var(--pa-t-xs); }

        .usage-guide > summary::after {
          width: 0.875rem;
          height: 0.875rem;
          flex: 0 0 auto;
          background: currentColor;
          content: "";
          mask: var(--pa-icon-chevron) center / contain no-repeat;
          -webkit-mask: var(--pa-icon-chevron) center / contain no-repeat;
          transition: transform var(--pa-fast) var(--pa-ease);
        }

        .usage-guide[open] > summary { border-bottom: 1px solid var(--pa-line); background: var(--pa-surface-2); }
        .usage-guide[open] > summary::after { transform: rotate(90deg); }
        .usage-guide-hint { margin-left: auto; color: var(--pa-text-3); font-size: var(--pa-t-2xs); font-weight: 400; }
        .usage-guide-body { padding: 0.25rem 0.875rem 0.5rem; }
        .usage-classification-list { margin: 0; padding: 0; }
        .usage-classification-row { display: grid; min-width: 0; grid-template-columns: minmax(11rem, 13rem) minmax(0, 1fr); gap: 0.875rem; align-items: center; padding: 0.5rem 0; }
        .usage-classification-row + .usage-classification-row { border-top: 1px solid var(--pa-line); }
        .usage-classification-row dt, .usage-classification-row dd { min-width: 0; margin: 0; }
        .usage-classification-row dd { color: var(--pa-text-2); font-size: var(--pa-t-xs); overflow-wrap: anywhere; }

        /* Objects inside an already-bordered card are laid out as a hairline matrix rather than as a grid
           of little cards: each cell draws its own 1px ring, neighbouring rings overlap in the 1px gap,
           and the result reads as one table instead of boxes inside a box. */
        .object-list, .semantic-object-list, .related-findings {
          display: grid;
          min-width: 0;
          grid-template-columns: repeat(auto-fit, minmax(min(100%, 16rem), 1fr));
          gap: 1px;
          margin: 0.5rem 0 0.875rem;
          padding: 0;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          list-style: none;
          overflow: clip;
        }

        .object-list.compact { margin-bottom: 0; }

        .object-list li, .semantic-object, .related-findings li {
          min-width: 0;
          max-width: 100%;
          padding: 0.4375rem 0.625rem;
          background: var(--pa-surface);
          box-shadow: 0 0 0 1px var(--pa-line);
          font-size: var(--pa-t-xs);
          overflow-wrap: anywhere;
        }

        .object-list li { display: flex; justify-content: space-between; gap: 0.625rem; }
        .semantic-object { padding: 0.5rem 0.625rem; transition: background var(--pa-fast) var(--pa-ease); }
        .semantic-object:hover { background: var(--pa-surface-2); }
        .semantic-object-header { display: flex; min-width: 0; max-width: 100%; flex-wrap: wrap; align-items: flex-start; justify-content: space-between; gap: 0.375rem 0.625rem; }
        .object-list li > span, .object-name > span { color: var(--pa-text-2); font-size: var(--pa-t-2xs); }
        .object-name { display: flex; min-width: 0; flex: 1 1 12rem; flex-direction: column; font-size: var(--pa-t-xs); font-weight: 600; overflow-wrap: anywhere; }
        .semantic-object[data-usage-state="StructurallyRequired"] .object-name { flex-basis: 8rem; }
        .usage-reason { min-width: 0; max-width: 100%; margin: 0.375rem 0 0; color: var(--pa-text-2); font-size: var(--pa-t-2xs); overflow-wrap: anywhere; }

        .semantic-feature {
          min-width: 0;
          max-width: 100%;
          margin: 0.625rem 0.875rem;
          padding: 0.625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-left: 3px solid var(--pa-structural);
          border-radius: var(--pa-r2);
          background: var(--pa-surface-2);
          overflow-wrap: anywhere;
        }

        .semantic-feature h4 { margin: 0 0 0.25rem; font-size: var(--pa-t-xs); }
        .semantic-feature p { margin: 0 0 0.25rem; font-size: var(--pa-t-xs); }
        .calculation-item { display: block !important; }
        .semantic-expression { margin-top: 0.5rem; }
        .calculated-table-expression { width: calc(100% - 1.75rem); margin: 0.625rem 0.875rem 0; box-sizing: border-box; }

        .usage-details { min-width: 0; max-width: 100%; margin-top: 0.5rem; padding-top: 0.375rem; border-top: 1px solid var(--pa-line); }
        .usage-location-groups { display: grid; min-width: 0; max-width: 100%; gap: 0.75rem; margin-top: 0.5rem; }
        .usage-page-group { min-width: 0; max-width: 100%; padding-left: 0.625rem; border-left: 2px solid var(--pa-line-strong); }
        .usage-page-group + .usage-page-group { padding-top: 0.625rem; border-top: 1px solid var(--pa-line); }
        .usage-page-heading { min-width: 0; margin: 0 0 0.25rem; }
        .usage-group-type { display: block; color: var(--pa-text-3); font-size: var(--pa-t-3xs); font-weight: 650; letter-spacing: 0.08em; text-transform: uppercase; }
        .usage-page-group h5 { margin: 0.0625rem 0 0; color: var(--pa-text); font-size: var(--pa-t-xs); overflow-wrap: anywhere; }
        .usage-report { margin: 0 0 0.25rem; color: var(--pa-text-2); font-size: var(--pa-t-2xs); }
        .usage-label { font-weight: 650; }
        .usage-page-kind { margin: 0.0625rem 0 0; color: var(--pa-text-3); font-size: var(--pa-t-2xs); font-weight: 400; }
        .usage-location-list { display: grid; min-width: 0; max-width: 100%; gap: 0.375rem; margin: 0; padding: 0; list-style: none; font-size: var(--pa-t-xs); }
        .usage-location-list li { display: grid; min-width: 0; max-width: 100%; gap: 0.0625rem; padding: 0.3125rem 0; border: 0; border-top: 1px solid var(--pa-line); border-radius: 0; background: transparent; overflow-wrap: anywhere; }
        .usage-location-list li:first-child { border-top: 0; }
        .usage-visual, .usage-context, .usage-role { min-width: 0; }
        .usage-role { color: var(--pa-text-2); font-size: var(--pa-t-2xs); }
        .plain-list { margin: 0.375rem 0 0.75rem; font-size: var(--pa-t-xs); }
        .related-findings li { display: flex; align-items: flex-start; gap: 0.375rem; }
        .object-list li > span, .semantic-object .object-name > span { font-weight: 400; }

        /* ------------------------------------------------------------- Power Query */

        .power-query-context {
          min-width: 0;
          max-width: 100%;
          margin: 0.625rem 0.875rem 0.875rem;
          padding: 0.625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-left: 3px solid var(--pa-accent);
          border-radius: var(--pa-r2);
          background: var(--pa-surface-2);
          overflow-wrap: anywhere;
        }

        .power-query-context h4 { margin: 0 0 0.25rem; color: var(--pa-text); font-size: var(--pa-t-xs); }
        .power-query-context p { margin: 0.1875rem 0; font-size: var(--pa-t-xs); }
        .query-card-body { min-width: 0; max-width: 100%; padding: 0.75rem 0.875rem 0.875rem; }
        .query-model-association { margin: 0 0 0.5rem; color: var(--pa-text-2); font-size: var(--pa-t-xs); overflow-wrap: anywhere; }

        .query-dependencies {
          min-width: 0;
          max-width: 100%;
          padding: 0.5625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface-2);
        }

        .query-dependencies h4 { margin: 0 0 0.375rem; color: var(--pa-text-3); font-size: var(--pa-t-3xs); font-weight: 650; letter-spacing: 0.08em; text-transform: uppercase; }
        .query-dependency-grid { display: grid; min-width: 0; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 0.5rem 1rem; margin: 0; }
        .query-dependency-grid div { min-width: 0; }
        .query-dependency-grid dt { color: var(--pa-text-3); font-size: var(--pa-t-2xs); font-weight: 650; }
        .query-dependency-grid dd { min-width: 0; margin: 0.0625rem 0 0; font-size: var(--pa-t-xs); overflow-wrap: anywhere; }
        .query-link-row { min-width: 0; margin: 0.0625rem 0 0; overflow-wrap: anywhere; }
        .query-dependencies .secondary { margin: 0.375rem 0 0; font-size: var(--pa-t-2xs); }

        .query-review, .relationship-review, .rls-coverage-note, .theme-comparison-state {
          margin: 0.5rem 0 0;
          padding: 0.5rem 0.625rem;
          border: 1px solid var(--pa-info-line);
          border-left: 3px solid var(--pa-info);
          border-radius: var(--pa-r2);
          background: var(--pa-info-soft);
          font-size: var(--pa-t-xs);
          overflow-wrap: anywhere;
        }

        .power-query-card .technical-details { margin-top: 0.625rem; }

        .power-query-column-context {
          min-width: 0;
          max-width: 100%;
          margin: 0.5rem 0 0;
          padding: 0.5625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface-2);
          overflow-wrap: anywhere;
        }

        .power-query-column-context p { margin: 0.25rem 0; color: var(--pa-text-2); font-size: var(--pa-t-2xs); }
        .power-query-column-context .plain-list { margin: 0.3125rem 0 0; }
        .power-query-column-context.compact > summary { font-size: var(--pa-t-xs); }

        /* ---------------------------------------------------------- relationships */

        .relationship-body { min-width: 0; max-width: 100%; padding: 0.75rem 0.875rem; }
        .relationship-facts { display: grid; min-width: 0; grid-template-columns: repeat(auto-fit, minmax(min(100%, 12rem), 1fr)); gap: 0; margin: 0; border: 1px solid var(--pa-line); border-radius: var(--pa-r2); background: var(--pa-surface-2); overflow: clip; }
        .relationship-facts div { min-width: 0; padding: 0.4375rem 0.625rem; border-left: 1px solid var(--pa-line); }
        .relationship-facts div:first-child { border-left: 0; }
        .relationship-facts dt { color: var(--pa-text-3); font-size: var(--pa-t-2xs); font-weight: 650; }
        .relationship-facts dd { margin: 0.0625rem 0 0; font-size: var(--pa-t-xs); font-weight: 600; overflow-wrap: anywhere; }

        /* ------------------------------------------------------- row-level security */

        .rls-model-list, .rls-role-list, .rls-filter-list { display: grid; min-width: 0; gap: 0.5rem; }
        .rls-model + .rls-model { margin-top: 1.5rem; padding-top: 1.25rem; border-top: 1px solid var(--pa-line); }
        .rls-model > h3 { margin: 0 0 0.125rem; }
        .rls-model > .secondary { margin: 0 0 0.625rem; font-size: var(--pa-t-xs); }
        .rls-role-body { min-width: 0; max-width: 100%; padding: 0.75rem 0.875rem 0.875rem; }
        .rls-role-body > :first-child { margin-top: 0; }
        .rls-role-body h4 { margin: 0.75rem 0 0.375rem; }
        .rls-role-facts { margin-bottom: 0.75rem; }
        .rls-filter-list { grid-template-columns: repeat(auto-fit, minmax(min(100%, 22rem), 1fr)); }

        .rls-filter {
          min-width: 0;
          max-width: 100%;
          padding: 0.5625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface-2);
        }

        .rls-filter h5 { display: grid; gap: 0.0625rem; margin: 0 0 0.375rem; font-size: var(--pa-t-xs); overflow-wrap: anywhere; }
        .rls-filter h5 span { color: var(--pa-text-3); font-family: var(--pa-font-sans); font-size: var(--pa-t-3xs); font-weight: 650; letter-spacing: 0.08em; text-transform: uppercase; }
        .rls-filter pre { max-width: 100%; margin: 0; padding: 0.5625rem 0.625rem; overflow-x: auto; border: 1px solid var(--pa-line); border-radius: var(--pa-r1); background: var(--pa-surface); font-size: var(--pa-t-2xs); white-space: pre-wrap; overflow-wrap: anywhere; }
        .rls-filter pre code { white-space: inherit; }

        /* --------------------------------------------------------------- findings */

        .finding-location { display: grid; gap: 0.375rem; margin: 0; font-size: var(--pa-t-xs); }
        .finding-location div { display: grid; min-width: 0; grid-template-columns: minmax(4.5rem, auto) minmax(0, 1fr); gap: 0.625rem; }
        .finding-location dt { color: var(--pa-text-3); font-weight: 650; }
        .finding-location dd { margin: 0; overflow-wrap: anywhere; }
        .inventory-link { display: inline-block; margin-top: 0.5rem; font-size: var(--pa-t-xs); font-weight: 600; }

        .technical-details { min-width: 0; max-width: 100%; margin-top: 0.875rem; padding-top: 0.375rem; border-top: 1px solid var(--pa-line); color: var(--pa-text-2); font-size: var(--pa-t-xs); overflow-wrap: anywhere; }
        .technical-details > summary { font-size: var(--pa-t-2xs); }
        .technical-details pre { max-width: 100%; overflow-x: auto; }
        .technical-list { display: grid; gap: 0.3125rem; padding: 0; }
        .technical-list div { display: grid; min-width: 0; grid-template-columns: minmax(6rem, auto) minmax(0, 1fr); gap: 0.625rem; }
        .technical-list dt { color: var(--pa-text-3); font-weight: 650; }
        .technical-list dd, .facts dd { min-width: 0; margin: 0; overflow-wrap: anywhere; }

        details:target { outline: 2px solid var(--pa-focus); outline-offset: 2px; }

        pre {
          padding: 0.625rem 0.75rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface-2);
          font-size: var(--pa-t-2xs);
          line-height: 1.5;
        }

        /* ----------------------------------------------------------- theme review */

        .theme-check-summary { margin: 0.75rem 0; }
        .theme-empty-state { margin: 0.75rem 0 0; padding: 0.625rem 0.75rem; border: 1px solid var(--pa-line); border-radius: var(--pa-r2); background: var(--pa-surface); color: var(--pa-text-2); font-size: var(--pa-t-xs); }
        .theme-governance-list { display: grid; gap: 0.5rem; margin-top: 0.75rem; }

        .theme-governance-card {
          min-width: 0;
          padding: 0.75rem 0.875rem;
          border: 1px solid var(--pa-line);
          border-left: 3px solid var(--pa-warning);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
          overflow-wrap: anywhere;
        }

        .theme-governance-card h4 { margin: 0.1875rem 0 0.3125rem; font-size: var(--pa-t-sm); }
        .theme-governance-card p { margin: 0.25rem 0; font-size: var(--pa-t-xs); }
        .theme-affected-visual { margin: 0.25rem 0 0.4375rem; color: var(--pa-text); font-size: var(--pa-t-xs); }
        .theme-affected-visual ul { margin: 0.25rem 0 0; padding-left: 1.125rem; }
        .theme-affected-visual li + li { margin-top: 0.125rem; }
        .theme-review-kind { display: inline-block; color: var(--pa-warning); font-size: var(--pa-t-3xs); font-weight: 650; letter-spacing: 0.08em; text-transform: uppercase; }
        .theme-example-list { margin: 0.375rem 0 0; padding-left: 1.125rem; font-size: var(--pa-t-xs); }
        .theme-example-list li + li { margin-top: 0.25rem; }

        .theme-supporting-details { min-width: 0; max-width: 100%; margin-top: 1.25rem; border: 1px solid var(--pa-line); border-radius: var(--pa-r2); background: var(--pa-surface); }
        .theme-supporting-details > summary { padding: 0.6875rem 0.875rem; font-size: var(--pa-t-xs); }
        .theme-supporting-body { min-width: 0; max-width: 100%; padding: 0 0.875rem 0.875rem; }
        .theme-supporting-body > .theme-review-group:first-child { margin-top: 0.25rem; }
        .theme-review-group + .theme-review-group { margin-top: 1.5rem; padding-top: 1rem; border-top: 1px solid var(--pa-line); }
        .theme-review-group > h3 { margin: 0 0 0.5rem; }
        .theme-report-list, .theme-content-grid, .theme-visual-list { display: grid; min-width: 0; gap: 0.5rem; }
        .theme-report-list, .theme-content-grid { grid-template-columns: repeat(auto-fit, minmax(min(100%, 25rem), 1fr)); }

        .theme-report-card, .theme-content-card {
          min-width: 0;
          padding: 0.75rem 0.875rem;
          border: 1px solid var(--pa-line);
          border-radius: var(--pa-r2);
          background: var(--pa-surface);
        }

        .theme-report-card h4, .theme-content-report > h4, .theme-content-card h5 { margin: 0 0 0.375rem; font-size: var(--pa-t-sm); }
        .theme-state { margin: 0 0 0.5rem; color: var(--pa-text-2); font-size: var(--pa-t-xs); font-weight: 600; }
        .theme-source-summary, .theme-content-facts, .theme-metadata-grid dl { display: grid; gap: 0.3125rem; margin: 0.4375rem 0; font-size: var(--pa-t-xs); }
        .theme-source-summary div, .theme-content-facts div, .theme-metadata-grid dl div { display: grid; min-width: 0; grid-template-columns: minmax(7rem, 10rem) minmax(0, 1fr); gap: 0.625rem; }
        .theme-source-summary dt, .theme-content-facts dt, .theme-metadata-grid dt { color: var(--pa-text-3); font-weight: 650; }
        .theme-source-summary dd, .theme-content-facts dd, .theme-metadata-grid dd { min-width: 0; margin: 0; overflow-wrap: anywhere; }

        .theme-resolution-issues { margin-top: 0.75rem; padding: 0.5625rem 0.75rem; border: 1px solid var(--pa-warning-line); border-left: 3px solid var(--pa-warning); border-radius: var(--pa-r2); background: var(--pa-warning-soft); font-size: var(--pa-t-xs); }
        .theme-resolution-issues ul { margin-bottom: 0; padding-left: 1.125rem; }
        .theme-content-report { min-width: 0; margin-top: 1rem; }
        .theme-palette { display: grid; grid-template-columns: repeat(auto-fill, minmax(1.5rem, 1.5rem)); min-width: 0; max-width: 100%; gap: 0.3125rem; margin: 0.625rem 0 0.3125rem; padding: 0; list-style: none; }
        .theme-swatch { display: grid; width: 1.5rem; height: 1.5rem; overflow: hidden; border: 1px solid var(--pa-line-strong); border-radius: var(--pa-r1); background: var(--swatch); }
        .theme-colour-value { display: inline-flex; min-width: 0; align-items: center; gap: 0.3125rem; vertical-align: middle; }
        .theme-colour-chip { flex: 0 0 auto; width: 0.9375rem; height: 0.9375rem; border: 1px solid var(--pa-line-strong); border-radius: 2px; background: var(--colour-chip); }
        .theme-metadata-grid { min-width: 0; margin-top: 0.75rem; padding-top: 0.5625rem; border-top: 1px solid var(--pa-line); }
        .theme-metadata-grid h6 { margin: 0; color: var(--pa-text-3); font-size: var(--pa-t-3xs); font-weight: 650; letter-spacing: 0.08em; text-transform: uppercase; }
        .theme-visual-body { min-width: 0; padding: 0.625rem 0.875rem 0.75rem; }
        .theme-observation-list { display: grid; min-width: 0; grid-template-columns: repeat(auto-fit, minmax(min(100%, 22rem), 1fr)); gap: 0.5rem; }
        .theme-observation { min-width: 0; padding: 0.5625rem 0.75rem; border: 1px solid var(--pa-line); border-radius: var(--pa-r2); background: var(--pa-surface-2); font-size: var(--pa-t-xs); overflow-wrap: anywhere; }
        .theme-observation p { margin: 0.375rem 0 0; }
        .theme-comparison-state { margin: 0.375rem 0 0; }

        /* ------------------------------------------------------------------ footer */

        .site-footer { margin-top: 1.5rem; padding: 1rem 0 1.5rem; border-top: 1px solid var(--pa-line); color: var(--pa-text-3); font-size: var(--pa-t-2xs); }
        .site-footer p { margin: 0; }

        /* ------------------------------------------------------------------ layout */

        @media (min-width: 72rem) {
          .report-workspace { display: grid; grid-template-columns: 13rem minmax(0, 1fr); gap: 2rem; align-items: start; }
          .section-navigator { position: sticky; top: 1rem; max-height: calc(100vh - 2rem); overflow-y: auto; margin-top: 1.5rem; padding: 0; }
          .section-nav { grid-template-columns: minmax(0, 1fr); gap: 1px; margin: 0; }

          /* On the rail the description is redundant and the row becomes a single scannable line with a
             2px active edge instead of a boxed button. */
          .section-nav a {
            padding: 0.375rem 0.625rem 0.375rem 0.5rem;
            border: 0;
            border-left: 2px solid transparent;
            border-radius: var(--pa-r1);
            background: transparent;
          }

          .section-nav small { display: none; }
          .section-nav a:hover { border-left-color: var(--pa-line-strong); background: var(--pa-surface-2); }
          .section-nav a[aria-current="page"] { border-left-color: var(--pa-accent); background: var(--pa-accent-soft); color: var(--pa-accent); font-weight: 600; }
          .section-nav li:has(> a[href="#findings"]), .section-nav li:has(> a[href="#theme-review"]) { margin-top: 0.5rem; padding-top: 0.5rem; border-top: 1px solid var(--pa-line); }
        }

        @media (max-width: 45rem) {
          .content { width: min(100% - 1.5rem, 82rem); }
          .section-nav { grid-template-columns: repeat(2, minmax(0, 1fr)); }
          .section-nav a { min-height: 2.5rem; }
          .section-nav small { display: none; }
          .site-header-identity { padding: 0.625rem 0 0.75rem; }
          h1 { font-size: var(--pa-t-xl); }
          h2 { font-size: var(--pa-t-lg); }
          .filters { display: block; }
          .filters div + div { margin-top: 0.75rem; }
          .finding-investigation { padding: 0.625rem; }
          .finding-facet-grid { grid-template-columns: 1fr; }
          .rule-catalogue-list { grid-template-columns: 1fr; }
          .finding-card > summary, .accessibility-finding-card > summary, .page-card > summary, .relationship-card > summary, .visual-card > summary, .semantic-table > summary { gap: 0.5rem; padding: 0.625rem; }
          .card-body, .page-body, .visual-body { padding: 0.625rem; }
          .power-query-card > summary { flex-wrap: wrap; }
          .query-card-body { padding: 0.625rem; }
          .query-dependency-grid { grid-template-columns: 1fr; }
          .object-list, .semantic-object-list { grid-template-columns: 1fr; }
          .usage-classification-row { grid-template-columns: 1fr; gap: 0.25rem; align-items: start; }
          .count-pill { white-space: normal; }
          .technical-list div, .finding-location div { grid-template-columns: 1fr; gap: 0.125rem; }
          .theme-source-summary div, .theme-content-facts div, .theme-metadata-grid dl div { grid-template-columns: 1fr; gap: 0.0625rem; }
          .theme-governance-card { padding: 0.625rem; }
          .theme-supporting-body { padding: 0 0.625rem 0.75rem; }
          .metrics { grid-template-columns: repeat(auto-fit, minmax(7rem, 1fr)); }
          .fact-strip, .relationship-facts { grid-template-columns: minmax(0, 1fr); }
          .fact-strip div, .relationship-facts div { border-left: 0; border-top: 1px solid var(--pa-line); }
          .fact-strip div:first-child, .relationship-facts div:first-child { border-top: 0; }
        }

        @media print {
          body { background: #fff; color: #000; }
          .report-workspace { display: block; }
          .skip-link, .section-navigator, .filters, .filter-status, .details-controls, .finding-investigation, .finding-results-row, .filter-chips, .finding-empty-state, .info-tooltip, .appearance-control { display: none; }
          .report-section[hidden] { display: block !important; }
          main > section { break-inside: avoid; }
          details { break-inside: avoid; }
          a { color: #000; }
        }

        /* ------------------------------------------------------- section glyphs */

        :root {
          --pa-icon-summary: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M2.4 2.2h11.2c.44 0 .8.36.8.8v10c0 .44-.36.8-.8.8H2.4a.8.8 0 0 1-.8-.8V3c0-.44.36-.8.8-.8Zm.7 1.5v8.6h9.8V3.7Z'/%3E%3Cpath d='M4.6 9.4h1.5v1.7H4.6zm2.7-2.6h1.5v4.3H7.3zm2.7-1.7h1.5v6H10z'/%3E%3C/svg%3E");
          --pa-icon-model: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 1.4c3.1 0 5.5 1 5.5 2.4v8.4c0 1.4-2.4 2.4-5.5 2.4s-5.5-1-5.5-2.4V3.8C2.5 2.4 4.9 1.4 8 1.4Zm4 4.9c-1 .5-2.4.8-4 .8s-3-.3-4-.8v2c.1.4 1.7 1.1 4 1.1s3.9-.7 4-1.1Zm0 4.1c-1 .5-2.4.8-4 .8s-3-.3-4-.8v1.7c.1.4 1.7 1.1 4 1.1s3.9-.7 4-1.1ZM8 2.9c-2.3 0-3.9.7-4 1s1.7 1 4 1 3.9-.7 4-1-1.7-1-4-1Z'/%3E%3C/svg%3E");
          --pa-icon-query: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M5.9 2.2a.75.75 0 0 1 .1 1.06L3.47 6.2a.6.6 0 0 0 0 .78L6 9.94a.75.75 0 1 1-1.14.98L2.33 7.96a2.1 2.1 0 0 1 0-2.72L4.86 2.3a.75.75 0 0 1 1.05-.1Zm4.2 0a.75.75 0 0 1 1.05.1l2.52 2.94a2.1 2.1 0 0 1 0 2.72l-2.52 2.96a.75.75 0 1 1-1.14-.98l2.52-2.96a.6.6 0 0 0 0-.78L10.01 3.26a.75.75 0 0 1 .09-1.06Z'/%3E%3Cpath d='M6.3 12.6h6.2v1.4H6.3z'/%3E%3C/svg%3E");
          --pa-icon-relationship: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Ccircle cx='3.7' cy='8' r='2.3'/%3E%3Ccircle cx='12.3' cy='3.6' r='2.1'/%3E%3Ccircle cx='12.3' cy='12.4' r='2.1'/%3E%3Cpath d='M5.6 7.1 10.5 4.6l.65 1.3-4.9 2.5zm0 1.8.65-1.3 4.9 2.5-.65 1.3z'/%3E%3C/svg%3E");
          --pa-icon-security: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 1.3l5.3 2.1v4.2c0 3-2.1 5.7-5.3 6.9-3.2-1.2-5.3-3.9-5.3-6.9V3.4Zm0 1.6L4.2 4.4v3.2c0 2.2 1.5 4.3 3.8 5.3 2.3-1 3.8-3.1 3.8-5.3V4.4Z'/%3E%3Ccircle cx='8' cy='7' r='1.5'/%3E%3Cpath d='M7.3 8h1.4v2.6H7.3z'/%3E%3C/svg%3E");
          --pa-icon-pages: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M2.4 2.2h11.2c.44 0 .8.36.8.8v10c0 .44-.36.8-.8.8H2.4a.8.8 0 0 1-.8-.8V3c0-.44.36-.8.8-.8Zm.7 1.5v1.5h9.8V3.7Zm0 3v5.6h3.4V6.7Zm4.9 0v5.6h4.9V6.7Z'/%3E%3C/svg%3E");
          --pa-icon-findings: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M7.1 1.5a5.6 5.6 0 1 1-3.4 10.05l-2.06 2.06a.85.85 0 0 1-1.2-1.2l2.06-2.06A5.6 5.6 0 0 1 7.1 1.5Zm0 1.7a3.9 3.9 0 1 0 0 7.8 3.9 3.9 0 0 0 0-7.8Z'/%3E%3Cpath d='M6.35 4.6h1.5v3h-1.5zm0 3.9h1.5V10h-1.5z'/%3E%3C/svg%3E");
          --pa-icon-coverage: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 1.4a6.6 6.6 0 1 1 0 13.2A6.6 6.6 0 0 1 8 1.4Zm0 1.6a5 5 0 1 0 0 10 5 5 0 0 0 0-10Z'/%3E%3Cpath d='M8 3.6a4.4 4.4 0 0 1 4.4 4.4H8Z'/%3E%3C/svg%3E");
          --pa-icon-theme: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M8 1.5c3.6 0 6.5 2.6 6.5 5.9 0 1.9-1.6 3.4-3.5 3.4h-1.2c-.6 0-1.1.5-1.1 1.1 0 .3.1.5.3.7.2.2.3.5.3.8 0 .6-.5 1.1-1.3 1.1-3.6 0-6.5-2.9-6.5-6.5S4.4 1.5 8 1.5Zm0 1.5a5 5 0 0 0 0 10c0-.2 0-.3-.1-.4a2.6 2.6 0 0 1 1.9-4.3H11c1.1 0 2-.8 2-1.9C13 4.7 10.8 3 8 3Z'/%3E%3Ccircle cx='5.3' cy='6.2' r='1.1'/%3E%3Ccircle cx='8' cy='4.7' r='1.1'/%3E%3Ccircle cx='10.7' cy='6.2' r='1.1'/%3E%3C/svg%3E");
          --pa-icon-accessibility: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Ccircle cx='8' cy='3' r='1.6'/%3E%3Cpath d='M2.6 5.1a.8.8 0 0 1 .95-.6c1.3.3 2.8.5 4.45.5s3.15-.2 4.45-.5a.8.8 0 1 1 .35 1.55c-1.1.25-2.3.4-3.6.47v1.6l1.9 4.9a.8.8 0 1 1-1.5.57L8 9.9l-1.6 3.7a.8.8 0 0 1-1.5-.58l1.9-4.9v-1.6c-1.3-.07-2.5-.22-3.6-.47a.8.8 0 0 1-.6-.95Z'/%3E%3C/svg%3E");
        }
        """;
}
