using System.Globalization;
using System.Text;
using System.Text.Encodings.Web;
using PbiAssure.Core.Inventory;

namespace PbiAssure.Reporting;

public static class HtmlReportRenderer
{
    public static string Render(ProjectInventory inventory)
    {
        ArgumentNullException.ThrowIfNull(inventory);

        var html = new StringBuilder(capacity: 256_000);
        AppendDocumentStart(html, inventory);
        AppendSummary(html, inventory);
        AppendScope(html);
        AppendFindings(html, inventory);
        AppendReportInventory(html, inventory);
        AppendSemanticUsage(html, inventory);
        AppendDocumentEnd(html, inventory);
        return html.ToString();
    }

    private static void AppendDocumentStart(StringBuilder html, ProjectInventory inventory)
    {
        var projectName = ProjectName(inventory);

        html.AppendLine("<!doctype html>");
        html.AppendLine("<html lang=\"en-GB\">");
        html.AppendLine("<head>");
        html.AppendLine("  <meta charset=\"utf-8\">");
        html.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        html.Append("  <title>PBI Assure report — ").Append(Encode(projectName)).AppendLine("</title>");
        html.AppendLine("  <style>");
        html.AppendLine(Styles);
        html.AppendLine("  </style>");
        html.AppendLine("</head>");
        html.AppendLine("<body>");
        html.AppendLine("  <a class=\"skip-link\" href=\"#main-content\">Skip to main content</a>");
        html.AppendLine("  <header class=\"site-header\">");
        html.AppendLine("    <div class=\"content\">");
        html.AppendLine("      <p class=\"eyebrow\">Power BI metadata assurance</p>");
        html.Append("      <h1>").Append(Encode(projectName)).AppendLine("</h1>");
        html.Append("      <p class=\"lede\">Generated by PBI Assure from <code>")
            .Append(Encode(inventory.RootPath)).AppendLine("</code>.</p>");
        html.AppendLine("      <dl class=\"report-meta\">");
        AppendDefinition(html, "Scanned", inventory.ScannedAtUtc.UtcDateTime.ToString(
            "dd MMMM yyyy, HH:mm 'UTC'",
            CultureInfo.InvariantCulture));
        AppendDefinition(html, "Inventory schema", inventory.SchemaVersion);
        html.AppendLine("      </dl>");
        html.AppendLine("      <nav aria-label=\"Report sections\">");
        html.AppendLine("        <ul class=\"section-nav\">");
        html.AppendLine("          <li><a href=\"#summary\">Summary</a></li>");
        html.AppendLine("          <li><a href=\"#findings\">Findings</a></li>");
        html.AppendLine("          <li><a href=\"#reports\">Report inventory</a></li>");
        html.AppendLine("          <li><a href=\"#semantic-usage\">Semantic usage</a></li>");
        html.AppendLine("        </ul>");
        html.AppendLine("      </nav>");
        html.AppendLine("    </div>");
        html.AppendLine("  </header>");
        html.AppendLine("  <main id=\"main-content\" class=\"content\" tabindex=\"-1\">");
    }

    private static void AppendSummary(StringBuilder html, ProjectInventory inventory)
    {
        html.AppendLine("    <section id=\"summary\" aria-labelledby=\"summary-heading\">");
        html.AppendLine("      <h2 id=\"summary-heading\">Assurance summary</h2>");
        html.AppendLine("      <dl class=\"metrics\">");
        AppendMetric(html, "Errors", inventory.ErrorFindingCount, "metric-error");
        AppendMetric(html, "Warnings", inventory.WarningFindingCount, "metric-warning");
        AppendMetric(html, "Review required", inventory.ReviewRequiredCount, "metric-review");
        AppendMetric(html, "Total findings", inventory.FindingCount);
        AppendMetric(html, "Reports", inventory.ReportCount);
        AppendMetric(html, "Pages", inventory.PageCount);
        AppendMetric(html, "Visuals", inventory.VisualCount);
        AppendMetric(html, "Semantic objects", inventory.SemanticObjectUsages.Count);
        AppendMetric(html, "Directly used", inventory.DirectlyReferencedSemanticObjectCount);
        AppendMetric(html, "Apparently unused", inventory.ApparentlyUnusedSemanticObjectCount, "metric-unused");
        html.AppendLine("      </dl>");
        html.AppendLine("      <p class=\"summary-note\">Counts describe metadata found in the selected project. Review the analysis boundaries before acting on unused-object results.</p>");
        html.AppendLine("    </section>");
    }

    private static void AppendScope(StringBuilder html)
    {
        html.AppendLine("    <section class=\"scope\" aria-labelledby=\"scope-heading\">");
        html.AppendLine("      <h2 id=\"scope-heading\">Important interpretation boundaries</h2>");
        html.AppendLine("      <ul>");
        html.AppendLine("        <li><strong>Apparently unused</strong> means no usage was found in the analysed scope; it is not permission to delete an object.</li>");
        html.AppendLine("        <li>Bookmark-captured semantic state, Power Query M lineage, and external consumers are not yet complete dependency roots.</li>");
        html.AppendLine("        <li>Accessibility findings support manual WCAG and assistive-technology testing; they do not certify conformance.</li>");
        html.AppendLine("        <li>PBI Assure performs read-only analysis of the selected Power BI project.</li>");
        html.AppendLine("      </ul>");
        html.AppendLine("    </section>");
    }

    private static void AppendFindings(StringBuilder html, ProjectInventory inventory)
    {
        html.AppendLine("    <section id=\"findings\" aria-labelledby=\"findings-heading\">");
        html.AppendLine("      <h2 id=\"findings-heading\">Findings</h2>");
        if (inventory.Findings.Count == 0)
        {
            html.AppendLine("      <p>No automated findings were produced. Manual review is still required.</p>");
            html.AppendLine("    </section>");
            return;
        }

        html.AppendLine("      <div class=\"filters\" aria-label=\"Filter findings\">");
        html.AppendLine("        <div><label for=\"finding-search\">Search findings</label><input id=\"finding-search\" type=\"search\" autocomplete=\"off\"></div>");
        html.AppendLine("        <div><label for=\"finding-severity\">Severity</label><select id=\"finding-severity\"><option value=\"\">All severities</option><option>Error</option><option>Warning</option><option>Information</option></select></div>");
        html.AppendLine("        <div><label for=\"finding-category\">Category</label><select id=\"finding-category\"><option value=\"\">All categories</option>");
        foreach (var category in inventory.Findings
                     .Select(finding => finding.Category)
                     .Distinct(StringComparer.OrdinalIgnoreCase)
                     .OrderBy(category => category, StringComparer.OrdinalIgnoreCase))
        {
            html.Append("          <option>").Append(Encode(category)).AppendLine("</option>");
        }

        html.AppendLine("        </select></div>");
        html.AppendLine("      </div>");
        html.Append("      <p id=\"finding-filter-status\" class=\"filter-status\" role=\"status\">")
            .Append(inventory.Findings.Count.ToString(CultureInfo.InvariantCulture)).AppendLine(" findings shown.</p>");
        html.AppendLine("      <div class=\"table-scroll\">");
        html.AppendLine("        <table id=\"findings-table\">");
        html.AppendLine("          <caption>Automated findings, evidence, and recommended actions</caption>");
        html.AppendLine("          <thead><tr><th scope=\"col\">Severity</th><th scope=\"col\">Rule</th><th scope=\"col\">Finding</th><th scope=\"col\">Location and evidence</th><th scope=\"col\">Recommendation</th></tr></thead>");
        html.AppendLine("          <tbody>");
        foreach (var finding in inventory.Findings)
        {
            html.Append("            <tr data-severity=\"").Append(Encode(finding.Severity))
                .Append("\" data-category=\"").Append(Encode(finding.Category)).AppendLine("\">");
            html.Append("              <td><span class=\"badge ").Append(SeverityClass(finding.Severity))
                .Append("\">").Append(Encode(finding.Severity)).AppendLine("</span></td>");
            html.Append("              <td>");
            AppendRuleReference(html, finding);
            html.Append("<br><span class=\"secondary\">").Append(Encode(finding.Category))
                .Append(" · ").Append(Encode(finding.AssessmentType)).AppendLine("</span></td>");
            html.Append("              <td>").Append(Encode(finding.Message)).AppendLine("</td>");
            html.Append("              <td><strong>").Append(Encode(FormatLocation(finding))).AppendLine("</strong>");
            AppendEvidence(html, finding);
            html.AppendLine("              </td>");
            html.Append("              <td>").Append(Encode(finding.Recommendation)).AppendLine("</td>");
            html.AppendLine("            </tr>");
        }

        html.AppendLine("          </tbody>");
        html.AppendLine("        </table>");
        html.AppendLine("      </div>");
        html.AppendLine("    </section>");
    }

    private static void AppendReportInventory(StringBuilder html, ProjectInventory inventory)
    {
        html.AppendLine("    <section id=\"reports\" aria-labelledby=\"reports-heading\">");
        html.AppendLine("      <h2 id=\"reports-heading\">Report inventory</h2>");
        if (inventory.Reports.Count == 0)
        {
            html.AppendLine("      <p>No PBIR report definitions were found.</p>");
            html.AppendLine("    </section>");
            return;
        }

        html.AppendLine("      <div class=\"table-scroll\"><table>");
        html.AppendLine("        <caption>Reports and high-level metadata counts</caption>");
        html.AppendLine("        <thead><tr><th scope=\"col\">Report</th><th scope=\"col\">Pages</th><th scope=\"col\">Visuals</th><th scope=\"col\">Filters</th><th scope=\"col\">Bookmarks</th><th scope=\"col\">Actions</th><th scope=\"col\">Tooltip bindings</th></tr></thead><tbody>");
        foreach (var report in inventory.Reports)
        {
            html.Append("          <tr><th scope=\"row\">").Append(Encode(report.Name)).Append("</th>");
            AppendNumberCell(html, report.PageCount);
            AppendNumberCell(html, report.VisualCount);
            AppendNumberCell(html, report.FilterCount);
            AppendNumberCell(html, report.BookmarkCount);
            AppendNumberCell(html, report.ActionCount);
            AppendNumberCell(html, report.TooltipBindingCount);
            html.AppendLine("</tr>");
        }

        html.AppendLine("        </tbody></table></div>");
        html.AppendLine("      <h3>Pages</h3>");
        html.AppendLine("      <div class=\"table-scroll\"><table>");
        html.AppendLine("        <caption>Page roles, visibility, and contained metadata</caption>");
        html.AppendLine("        <thead><tr><th scope=\"col\">Report</th><th scope=\"col\">Page</th><th scope=\"col\">Role</th><th scope=\"col\">Visibility</th><th scope=\"col\">Visuals</th><th scope=\"col\">Filters</th><th scope=\"col\">Interactions</th><th scope=\"col\">Field references</th></tr></thead><tbody>");
        foreach (var report in inventory.Reports)
        {
            foreach (var page in report.Pages)
            {
                html.Append("          <tr><td>").Append(Encode(report.Name)).Append("</td><th scope=\"row\">")
                    .Append(Encode(page.DisplayName)).Append("</th><td>").Append(Encode(PageRole(page)))
                    .Append("</td><td>").Append(Encode(PageVisibility(page))).Append("</td>");
                AppendNumberCell(html, page.VisualCount);
                AppendNumberCell(html, page.FilterCount);
                AppendNumberCell(html, page.VisualInteractionCount);
                AppendNumberCell(html, page.FieldReferenceCount);
                html.AppendLine("</tr>");
            }
        }

        html.AppendLine("        </tbody></table></div>");
        html.AppendLine("      <h3>Visuals</h3>");
        html.AppendLine("      <div class=\"table-scroll\"><table>");
        html.AppendLine("        <caption>Visual types, semantic references, navigation, and detectable accessibility metadata</caption>");
        html.AppendLine("        <thead><tr><th scope=\"col\">Report</th><th scope=\"col\">Page</th><th scope=\"col\">Visual</th><th scope=\"col\">Type</th><th scope=\"col\">Fields</th><th scope=\"col\">Actions</th><th scope=\"col\">Tooltip pages</th><th scope=\"col\">Tab order</th><th scope=\"col\">Alt text</th></tr></thead><tbody>");
        foreach (var report in inventory.Reports)
        {
            foreach (var page in report.Pages)
            {
                foreach (var visual in page.Visuals)
                {
                    html.Append("          <tr><td>").Append(Encode(report.Name)).Append("</td><td>")
                        .Append(Encode(page.DisplayName)).Append("</td><th scope=\"row\"><code>")
                        .Append(Encode(visual.Name)).Append("</code></th><td>")
                        .Append(Encode(visual.VisualType ?? "Unknown")).Append("</td>");
                    AppendNumberCell(html, visual.FieldReferenceCount);
                    AppendNumberCell(html, visual.ActionCount);
                    AppendNumberCell(html, visual.TooltipBindingCount);
                    html.Append("<td>").Append(Encode(visual.Position.TabOrder?.ToString(CultureInfo.InvariantCulture) ?? "Excluded"))
                        .Append("</td><td>").Append(visual.Accessibility.HasAltText ? "Configured" : "Not detected")
                        .AppendLine("</td></tr>");
                }
            }
        }

        html.AppendLine("        </tbody></table></div>");
        html.AppendLine("    </section>");
    }

    private static void AppendSemanticUsage(StringBuilder html, ProjectInventory inventory)
    {
        html.AppendLine("    <section id=\"semantic-usage\" aria-labelledby=\"semantic-usage-heading\">");
        html.AppendLine("      <h2 id=\"semantic-usage-heading\">Semantic usage</h2>");
        if (inventory.SemanticModels.Count == 0)
        {
            html.AppendLine("      <p>No supported semantic model definition was found.</p>");
            html.AppendLine("    </section>");
            return;
        }

        html.AppendLine("      <div class=\"table-scroll\"><table>");
        html.AppendLine("        <caption>Semantic model inventory</caption>");
        html.AppendLine("        <thead><tr><th scope=\"col\">Model</th><th scope=\"col\">Tables</th><th scope=\"col\">Columns</th><th scope=\"col\">Measures</th><th scope=\"col\">Relationships</th></tr></thead><tbody>");
        foreach (var model in inventory.SemanticModels)
        {
            html.Append("          <tr><th scope=\"row\">").Append(Encode(model.Name)).Append("</th>");
            AppendNumberCell(html, model.TableCount);
            AppendNumberCell(html, model.ColumnCount);
            AppendNumberCell(html, model.MeasureCount);
            AppendNumberCell(html, model.RelationshipCount);
            html.AppendLine("</tr>");
        }

        html.AppendLine("        </tbody></table></div>");
        html.AppendLine("      <div class=\"filters\" aria-label=\"Filter semantic objects\">");
        html.AppendLine("        <div><label for=\"usage-search\">Search semantic objects</label><input id=\"usage-search\" type=\"search\" autocomplete=\"off\"></div>");
        html.AppendLine("        <div><label for=\"usage-state\">Usage state</label><select id=\"usage-state\"><option value=\"\">All usage states</option>");
        foreach (var state in inventory.SemanticObjectUsages
                     .Select(usage => usage.UsageState)
                     .Distinct(StringComparer.Ordinal)
                     .OrderBy(UsageOrder))
        {
            html.Append("          <option value=\"").Append(Encode(state)).Append("\">")
                .Append(Encode(UsageLabel(state))).AppendLine("</option>");
        }

        html.AppendLine("        </select></div>");
        html.AppendLine("      </div>");
        html.Append("      <p id=\"usage-filter-status\" class=\"filter-status\" role=\"status\">")
            .Append(inventory.SemanticObjectUsages.Count.ToString(CultureInfo.InvariantCulture)).AppendLine(" semantic objects shown.</p>");
        html.AppendLine("      <div class=\"table-scroll\"><table id=\"usage-table\">");
        html.AppendLine("        <caption>Semantic objects and evidence-backed usage classifications</caption>");
        html.AppendLine("        <thead><tr><th scope=\"col\">Model</th><th scope=\"col\">Table</th><th scope=\"col\">Object</th><th scope=\"col\">Type</th><th scope=\"col\">Usage state</th><th scope=\"col\">Direct evidence</th></tr></thead><tbody>");
        foreach (var usage in inventory.SemanticObjectUsages)
        {
            html.Append("          <tr data-usage-state=\"").Append(Encode(usage.UsageState)).Append("\"><td>")
                .Append(Encode(usage.SemanticModel)).Append("</td><td>").Append(Encode(usage.Table))
                .Append("</td><th scope=\"row\">").Append(Encode(usage.ObjectName)).Append("</th><td>")
                .Append(Encode(usage.ObjectType)).Append("</td><td><span class=\"badge ")
                .Append(UsageClass(usage.UsageState)).Append("\">").Append(Encode(UsageLabel(usage.UsageState)))
                .Append("</span></td>");
            AppendNumberCell(html, usage.DirectReportReferenceCount);
            html.AppendLine("</tr>");
        }

        html.AppendLine("        </tbody></table></div>");
        html.AppendLine("    </section>");
    }

    private static void AppendDocumentEnd(StringBuilder html, ProjectInventory inventory)
    {
        html.AppendLine("  </main>");
        html.AppendLine("  <footer class=\"site-footer\"><div class=\"content\">");
        html.Append("    <p>PBI Assure inventory schema ").Append(Encode(inventory.SchemaVersion))
            .AppendLine(". Generated locally from Power BI project metadata.</p>");
        html.AppendLine("  </div></footer>");
        html.AppendLine("  <script>");
        html.AppendLine(FilterScript);
        html.AppendLine("  </script>");
        html.AppendLine("</body>");
        html.AppendLine("</html>");
    }

    private static void AppendMetric(StringBuilder html, string label, int value, string? cssClass = null)
    {
        html.Append("        <div class=\"metric");
        if (cssClass is not null)
        {
            html.Append(' ').Append(cssClass);
        }

        html.Append("\"><dt>").Append(Encode(label)).Append("</dt><dd>")
            .Append(value.ToString("N0", CultureInfo.InvariantCulture)).AppendLine("</dd></div>");
    }

    private static string ProjectName(ProjectInventory inventory)
    {
        if (inventory.Reports.Count == 1)
        {
            return inventory.Reports[0].Name;
        }

        var directoryName = Path.GetFileName(inventory.RootPath.TrimEnd(
            Path.DirectorySeparatorChar,
            Path.AltDirectorySeparatorChar));
        return string.IsNullOrWhiteSpace(directoryName) ? "Power BI project" : directoryName;
    }

    private static void AppendDefinition(StringBuilder html, string term, string value)
    {
        html.Append("        <div><dt>").Append(Encode(term)).Append("</dt><dd>")
            .Append(Encode(value)).AppendLine("</dd></div>");
    }

    private static void AppendNumberCell(StringBuilder html, int value)
    {
        html.Append("<td class=\"number\">").Append(value.ToString("N0", CultureInfo.InvariantCulture)).Append("</td>");
    }

    private static void AppendRuleReference(StringBuilder html, AssuranceFinding finding)
    {
        if (finding.ReferenceUrl is not null && IsSafeHttpUrl(finding.ReferenceUrl))
        {
            html.Append("<a href=\"").Append(Encode(finding.ReferenceUrl)).Append("\"><code>")
                .Append(Encode(finding.RuleId)).Append("</code></a>");
        }
        else
        {
            html.Append("<code>").Append(Encode(finding.RuleId)).Append("</code>");
        }
    }

    private static void AppendEvidence(StringBuilder html, AssuranceFinding finding)
    {
        html.Append("                <details><summary>Evidence (")
            .Append(finding.EvidencePaths.Count.ToString(CultureInfo.InvariantCulture)).AppendLine(")</summary>");
        html.Append("                  <p><code>").Append(Encode(finding.ArtifactPath)).AppendLine("</code></p>");
        if (finding.EvidencePaths.Count > 0)
        {
            html.AppendLine("                  <ul>");
            foreach (var evidencePath in finding.EvidencePaths)
            {
                html.Append("                    <li><code>").Append(Encode(evidencePath)).AppendLine("</code></li>");
            }

            html.AppendLine("                  </ul>");
        }

        html.AppendLine("                </details>");
    }

    private static string FormatLocation(AssuranceFinding finding)
    {
        var values = new List<string>();
        AddIfPresent(values, finding.Report);
        AddIfPresent(values, finding.PageDisplayName ?? finding.Page);
        AddIfPresent(values, finding.Visual);
        AddIfPresent(values, finding.SemanticModel);
        AddIfPresent(values, finding.Table);
        AddIfPresent(values, finding.ObjectName);
        return values.Count == 0 ? "Project" : string.Join(" › ", values.Distinct(StringComparer.OrdinalIgnoreCase));
    }

    private static void AddIfPresent(List<string> values, string? value)
    {
        if (!string.IsNullOrWhiteSpace(value))
        {
            values.Add(value);
        }
    }

    private static string PageRole(PageInventory page)
    {
        if (string.Equals(page.PageBinding?.Type, "Drillthrough", StringComparison.OrdinalIgnoreCase))
        {
            return "Drillthrough";
        }

        return page.PageType ?? "Standard";
    }

    private static string PageVisibility(PageInventory page)
    {
        return string.Equals(page.Visibility, "HiddenInViewMode", StringComparison.OrdinalIgnoreCase)
            ? "Hidden in reading view"
            : "Visible";
    }

    private static string SeverityClass(string severity)
    {
        return severity switch
        {
            FindingSeverities.Error => "badge-error",
            FindingSeverities.Warning => "badge-warning",
            _ => "badge-information",
        };
    }

    private static string UsageClass(string usageState)
    {
        return usageState switch
        {
            SemanticUsageStates.DirectlyUsed => "badge-used",
            SemanticUsageStates.IndirectlyUsed => "badge-indirect",
            SemanticUsageStates.StructurallyRequired => "badge-structural",
            SemanticUsageStates.UsedOnlyByUnusedBranch => "badge-unused-branch",
            _ => "badge-unused",
        };
    }

    private static string UsageLabel(string usageState)
    {
        return usageState switch
        {
            SemanticUsageStates.DirectlyUsed => "Directly used",
            SemanticUsageStates.IndirectlyUsed => "Indirectly used",
            SemanticUsageStates.StructurallyRequired => "Structurally required",
            SemanticUsageStates.UsedOnlyByUnusedBranch => "Used only by unused branch",
            SemanticUsageStates.ApparentlyUnused => "Apparently unused",
            _ => usageState,
        };
    }

    private static int UsageOrder(string usageState)
    {
        return usageState switch
        {
            SemanticUsageStates.DirectlyUsed => 0,
            SemanticUsageStates.IndirectlyUsed => 1,
            SemanticUsageStates.StructurallyRequired => 2,
            SemanticUsageStates.UsedOnlyByUnusedBranch => 3,
            _ => 4,
        };
    }

    private static bool IsSafeHttpUrl(string value)
    {
        return Uri.TryCreate(value, UriKind.Absolute, out var uri) && uri.Scheme is "http" or "https";
    }

    private static string Encode(string value)
    {
        return HtmlEncoder.Default.Encode(value);
    }

    private const string Styles = """
    :root {
      color-scheme: light;
      --background: #f4f6f8;
      --surface: #ffffff;
      --text: #182230;
      --muted: #52606d;
      --border: #b8c2cc;
      --link: #004b87;
      --focus: #ffbf47;
      --error: #8b1e2d;
      --error-bg: #fdecef;
      --warning: #6b4600;
      --warning-bg: #fff3cd;
      --info: #174a73;
      --info-bg: #e8f3fb;
      --used: #145a32;
      --used-bg: #e8f6ee;
    }
    * { box-sizing: border-box; }
    html { scroll-behavior: smooth; }
    body { margin: 0; background: var(--background); color: var(--text); font-family: "Segoe UI", Arial, sans-serif; line-height: 1.5; }
    a { color: var(--link); text-decoration-thickness: .12em; text-underline-offset: .15em; }
    a:hover { text-decoration-thickness: .2em; }
    a:focus-visible, button:focus-visible, input:focus-visible, select:focus-visible, summary:focus-visible { outline: 4px solid var(--focus); outline-offset: 2px; }
    code { overflow-wrap: anywhere; font-size: .92em; }
    .skip-link { position: absolute; left: .75rem; top: -5rem; z-index: 10; padding: .75rem 1rem; background: #111827; color: #fff; font-weight: 700; }
    .skip-link:focus { top: .75rem; }
    .content { width: min(96rem, calc(100% - 2rem)); margin-inline: auto; }
    .site-header { background: #15324b; color: #fff; padding: 2.5rem 0 1.5rem; }
    .site-header code { color: #fff; }
    .site-header a { color: #fff; }
    .eyebrow { margin: 0 0 .25rem; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
    h1 { margin: 0; font-size: clamp(2rem, 5vw, 3.25rem); line-height: 1.1; }
    h2 { margin-top: 0; font-size: 1.7rem; }
    h3 { margin-top: 2rem; }
    .lede { max-width: 70rem; }
    .report-meta, .section-nav { display: flex; flex-wrap: wrap; gap: .75rem 1.5rem; margin: 1rem 0; padding: 0; }
    .report-meta div { display: flex; gap: .4rem; }
    .report-meta dt { font-weight: 700; }
    .report-meta dd { margin: 0; }
    .section-nav { list-style: none; }
    main > section { margin: 1.5rem 0; padding: 1.5rem; background: var(--surface); border: 1px solid var(--border); border-radius: .4rem; }
    .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr)); gap: .8rem; }
    .metric { padding: 1rem; border: 1px solid var(--border); border-left: .5rem solid #66788a; border-radius: .25rem; }
    .metric dt { color: var(--muted); font-weight: 700; }
    .metric dd { margin: .15rem 0 0; font-size: 2rem; font-weight: 750; }
    .metric-error { border-left-color: var(--error); }
    .metric-warning { border-left-color: #a66b00; }
    .metric-review { border-left-color: var(--info); }
    .metric-unused { border-left-color: #5b3f88; }
    .summary-note, .secondary, .filter-status { color: var(--muted); }
    .scope { border-left: .55rem solid var(--warning) !important; }
    .filters { display: flex; flex-wrap: wrap; gap: 1rem; align-items: end; margin: 1rem 0 .5rem; padding: 1rem; background: #eef2f6; border-radius: .3rem; }
    .filters div { min-width: min(100%, 14rem); flex: 1; }
    label { display: block; margin-bottom: .3rem; font-weight: 700; }
    input, select { width: 100%; min-height: 2.75rem; padding: .5rem; border: 2px solid #5f6c79; border-radius: .2rem; background: #fff; color: var(--text); font: inherit; }
    .table-scroll { max-width: 100%; overflow-x: auto; margin-block: 1rem; }
    table { width: 100%; border-collapse: collapse; background: #fff; }
    caption { padding: .6rem; text-align: left; font-size: 1.05rem; font-weight: 700; }
    th, td { padding: .65rem; border: 1px solid var(--border); text-align: left; vertical-align: top; }
    thead th { background: #e4eaf0; }
    tbody tr:nth-child(even) { background: #f8fafc; }
    tbody tr:hover { background: #fff8df; }
    .number { text-align: right; font-variant-numeric: tabular-nums; }
    .badge { display: inline-block; padding: .2rem .45rem; border: 1px solid currentColor; border-radius: .2rem; font-weight: 700; white-space: nowrap; }
    .badge-error { color: var(--error); background: var(--error-bg); }
    .badge-warning { color: var(--warning); background: var(--warning-bg); }
    .badge-information { color: var(--info); background: var(--info-bg); }
    .badge-used { color: var(--used); background: var(--used-bg); }
    .badge-indirect, .badge-structural { color: var(--info); background: var(--info-bg); }
    .badge-unused-branch, .badge-unused { color: #553080; background: #f2ecfa; }
    details { margin-top: .5rem; }
    summary { cursor: pointer; color: var(--link); font-weight: 650; }
    tr[hidden] { display: none; }
    .site-footer { padding: 1.5rem 0; color: var(--muted); }
    @media (max-width: 45rem) {
      .content { width: min(100% - 1rem, 96rem); }
      main > section { padding: 1rem .65rem; }
      .filters { display: block; }
      .filters div + div { margin-top: .8rem; }
    }
    @media print {
      body { background: #fff; }
      .skip-link, .section-nav, .filters, .filter-status { display: none; }
      main > section { break-inside: avoid; border-color: #777; }
      .table-scroll { overflow: visible; }
      a { color: #000; }
    }
    """;

    private const string FilterScript = """
    (() => {
      const normalise = value => (value || '').toLocaleLowerCase();

      const findingSearch = document.getElementById('finding-search');
      const findingSeverity = document.getElementById('finding-severity');
      const findingCategory = document.getElementById('finding-category');
      const findingTable = document.getElementById('findings-table');
      const findingStatus = document.getElementById('finding-filter-status');

      const filterFindings = () => {
        if (!findingTable) return;
        const query = normalise(findingSearch.value.trim());
        const severity = findingSeverity.value;
        const category = findingCategory.value;
        let visible = 0;
        findingTable.querySelectorAll('tbody tr').forEach(row => {
          const show = (!query || normalise(row.textContent).includes(query)) &&
            (!severity || row.dataset.severity === severity) &&
            (!category || row.dataset.category === category);
          row.hidden = !show;
          if (show) visible += 1;
        });
        findingStatus.textContent = `${visible} ${visible === 1 ? 'finding' : 'findings'} shown.`;
      };

      [findingSearch, findingSeverity, findingCategory].forEach(control => {
        if (control) control.addEventListener('input', filterFindings);
      });

      const usageSearch = document.getElementById('usage-search');
      const usageState = document.getElementById('usage-state');
      const usageTable = document.getElementById('usage-table');
      const usageStatus = document.getElementById('usage-filter-status');

      const filterUsage = () => {
        if (!usageTable) return;
        const query = normalise(usageSearch.value.trim());
        const state = usageState.value;
        let visible = 0;
        usageTable.querySelectorAll('tbody tr').forEach(row => {
          const show = (!query || normalise(row.textContent).includes(query)) &&
            (!state || row.dataset.usageState === state);
          row.hidden = !show;
          if (show) visible += 1;
        });
        usageStatus.textContent = `${visible} semantic ${visible === 1 ? 'object' : 'objects'} shown.`;
      };

      [usageSearch, usageState].forEach(control => {
        if (control) control.addEventListener('input', filterUsage);
      });
    })();
    """;
}
