<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PbiAssure.Reporting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PbiAssure.Core/PbiAssure.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>PbiAssure.Core.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
