table testData
	lineageTag: f0b9ea2f-2373-4544-878c-71ce6990962a

	column Category
		dataType: string
		lineageTag: 41a3412e-be34-42c3-9b2d-39c24e66a3c2
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 394d93f8-a51d-4e07-be8a-1f0b7167083f
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition testData = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WclTSUTJUitWJVnICsozALGcgyxjMcgGyTJRiYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, Value = _t]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"Category", type text}, {"Value", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
